from typing import List


def get_state_for_city(city: str) -> List[str]:
    city_state_mapping = {
        "mumbai": ["maharashtra"],
        "delhi": ["delhi"],
        "bengaluru": ["karnataka"],
        "ahmedabad": ["gujarat"],
        "hyderabad": ["telangana"],
        "chennai": ["tamil nadu"],
        "kolkata": ["west bengal"],
        "pune": ["maharashtra"],
        "jaipur": ["rajasthan"],
        "surat": ["gujarat"],
        "lucknow": ["uttar pradesh"],
        "kanpur": ["uttar pradesh"],
        "nagpur": ["maharashtra"],
        "patna": ["bihar"],
        "indore": ["madhya pradesh"],
        "thane": ["maharashtra"],
        "bhopal": ["madhya pradesh"],
        "visakhapatnam": ["andhra pradesh"],
        "vadodara": ["gujarat"],
        "firozabad": ["uttar pradesh"],
        "ludhiana": ["punjab"],
        "rajkot": ["gujarat"],
        "agra": ["uttar pradesh"],
        "siliguri": ["west bengal"],
        "nashik": ["maharashtra"],
        "faridabad": ["haryana"],
        "patiala": ["punjab"],
        "meerut": ["uttar pradesh"],
        "kalyan-dombivali": ["maharashtra"],
        "vasai-virar": ["maharashtra"],
        "varanasi": ["uttar pradesh"],
        "srinagar": ["jammu and kashmir", "uttarakhand"],
        "dhanbad": ["jharkhand"],
        "jodhpur": ["rajasthan"],
        "amritsar": ["punjab"],
        "raipur": ["chhattisgarh"],
        "allahabad": ["uttar pradesh"],
        "coimbatore": ["tamil nadu"],
        "jabalpur": ["madhya pradesh"],
        "gwalior": ["madhya pradesh"],
        "vijayawada": ["andhra pradesh"],
        "madurai": ["tamil nadu"],
        "guwahati": ["assam"],
        "chandigarh": ["chandigarh"],
        "hubli-dharwad": ["karnataka"],
        "amroha": ["uttar pradesh"],
        "moradabad": ["uttar pradesh"],
        "gurgaon": ["haryana"],
        "aligarh": ["uttar pradesh"],
        "solapur": ["maharashtra"],
        "ranchi": ["jharkhand"],
        "jalandhar": ["punjab"],
        "tiruchirappalli": ["tamil nadu"],
        "bhubaneswar": ["odisha"],
        "salem": ["tamil nadu"],
        "warangal": ["telangana"],
        "mira-bhayandar": ["maharashtra"],
        "thiruvananthapuram": ["kerala"],
        "bhiwandi": ["maharashtra"],
        "saharanpur": ["uttar pradesh"],
        "guntur": ["andhra pradesh"],
        "amravati": ["maharashtra"],
        "bikaner": ["rajasthan"],
        "noida": ["uttar pradesh"],
        "jamshedpur": ["jharkhand"],
        "bhilai nagar": ["chhattisgarh"],
        "cuttack": ["odisha"],
        "kochi": ["kerala"],
        "bhavnagar": ["gujarat"],
        "dehradun": ["uttarakhand"],
        "asansol": ["west bengal"],
        "nanded-waghala": ["maharashtra"],
        "ajmer": ["rajasthan"],
        "jamnagar": ["gujarat"],
        "ujjain": ["madhya pradesh"],
        "sangli": ["maharashtra"],
        "loni": ["uttar pradesh"],
        "jhansi": ["uttar pradesh"],
        "pondicherry": ["puducherry"],
        "nellore": ["andhra pradesh"],
        "jammu": ["jammu and kashmir"],
        "belagavi": ["karnataka"],
        "raurkela": ["odisha"],
        "mangaluru": ["karnataka"],
        "tirunelveli": ["tamil nadu"],
        "malegaon": ["maharashtra"],
        "gaya": ["bihar"],
        "tiruppur": ["tamil nadu"],
        "davanagere": ["karnataka"],
        "kozhikode": ["kerala"],
        "akola": ["maharashtra"],
        "kurnool": ["andhra pradesh"],
        "bokaro steel city": ["jharkhand"],
        "rajahmundry": ["andhra pradesh"],
        "ballari": ["karnataka"],
        "agartala": ["tripura"],
        "bhagalpur": ["bihar"],
        "latur": ["maharashtra"],
        "dhule": ["maharashtra"],
        "korba": ["chhattisgarh"],
        "bhilwara": ["rajasthan"],
        "brahmapur": ["odisha"],
        "mysore": ["karnatka"],
        "muzaffarpur": ["bihar"],
        "ahmednagar": ["maharashtra"],
        "kollam": ["kerala"],
        "raghunathganj": ["west bengal"],
        "bilaspur": ["chhattisgarh"],
        "shahjahanpur": ["uttar pradesh"],
        "thrissur": ["kerala"],
        "alwar": ["rajasthan"],
        "kakinada": ["andhra pradesh"],
        "nizamabad": ["telangana"],
        "sagar": ["madhya pradesh"],
        "tumkur": ["karnataka"],
        "hisar": ["haryana"],
        "rohtak": ["haryana"],
        "panipat": ["haryana"],
        "darbhanga": ["bihar"],
        "kharagpur": ["west bengal"],
        "aizawl": ["mizoram"],
        "ichalkaranji": ["maharashtra"],
        "tirupati": ["andhra pradesh"],
        "karnal": ["haryana"],
        "bathinda": ["punjab"],
        "rampur": ["uttar pradesh"],
        "shivamogga": ["karnataka"],
        "ratlam": ["madhya pradesh"],
        "modinagar": ["uttar pradesh"],
        "durg": ["chhattisgarh"],
        "shillong": ["meghalaya"],
        "imphal": ["manipur"],
        "hapur": ["uttar pradesh"],
        "ranipet": ["tamil nadu"],
        "anantapur": ["andhra pradesh"],
        "arrah": ["bihar"],
        "karimnagar": ["telangana"],
        "parbhani": ["maharashtra"],
        "etawah": ["uttar pradesh"],
        "bharatpur": ["rajasthan"],
        "begusarai": ["bihar"],
        "new delhi": ["delhi"],
        "chhapra": ["bihar", "gujarat"],
        "kadapa": ["andhra pradesh"],
        "ramagundam": ["telangana"],
        "satna": ["madhya pradesh"],
        "vizianagaram": ["andhra pradesh"],
        "katihar": ["bihar"],
        "hardwar": ["uttarakhand"],
        "sonipat": ["haryana"],
        "nagercoil": ["tamil nadu"],
        "thanjavur": ["tamil nadu"],
        "murwara (katni)": ["madhya pradesh"],
        "naihati": ["west bengal"],
        "sambhal": ["uttar pradesh"],
        "nadiad": ["gujarat"],
        "yamunanagar": ["haryana"],
        "english bazar": ["west bengal"],
        "eluru": ["andhra pradesh"],
        "munger": ["bihar"],
        "panchkula": ["haryana"],
        "raayachuru": ["karnataka"],
        "panvel": ["maharashtra"],
        "deoghar": ["jharkhand"],
        "ongole": ["andhra pradesh"],
        "nandyal": ["andhra pradesh"],
        "morena": ["madhya pradesh"],
        "bhiwani": ["haryana"],
        "porbandar": ["gujarat"],
        "palakkad": ["kerala"],
        "anand": ["gujarat"],
        "purnia": ["bihar"],
        "baharampur": ["west bengal"],
        "barmer": ["rajasthan"],
        "morvi": ["gujarat"],
        "orai": ["uttar pradesh"],
        "bahraich": ["uttar pradesh"],
        "sikar": ["rajasthan"],
        "vellore": ["tamil nadu"],
        "singrauli": ["madhya pradesh"],
        "khammam": ["telangana"],
        "mahesana": ["gujarat"],
        "silchar": ["assam"],
        "sambalpur": ["odisha"],
        "rewa": ["madhya pradesh"],
        "unnao": ["uttar pradesh"],
        "hugli-chinsurah": ["west bengal"],
        "raiganj": ["west bengal"],
        "phusro": ["jharkhand"],
        "adityapur": ["jharkhand"],
        "alappuzha": ["kerala"],
        "bahadurgarh": ["haryana"],
        "machilipatnam": ["andhra pradesh"],
        "rae bareli": ["uttar pradesh"],
        "jalpaiguri": ["west bengal"],
        "bharuch": ["gujarat"],
        "pathankot": ["punjab"],
        "hoshiarpur": ["punjab"],
        "baramula": ["jammu and kashmir"],
        "adoni": ["andhra pradesh"],
        "jind": ["haryana"],
        "tonk": ["rajasthan"],
        "tenali": ["andhra pradesh"],
        "kancheepuram": ["tamil nadu"],
        "sirsa": ["haryana"],
        "navsari": ["gujarat"],
        "mahbubnagar": ["telangana"],
        "puri": ["odisha"],
        "robertson pet": ["karnataka"],
        "erode": ["tamil nadu"],
        "batala": ["punjab"],
        "haldwani-cum-kathgodam": ["uttarakhand"],
        "vidisha": ["madhya pradesh"],
        "saharsa": ["bihar"],
        "thanesar": ["haryana"],
        "chittoor": ["andhra pradesh"],
        "veraval": ["gujarat"],
        "lakhimpur": ["uttar pradesh"],
        "sitapur": ["uttar pradesh"],
        "hindupur": ["andhra pradesh"],
        "santipur": ["west bengal"],
        "balurghat": ["west bengal"],
        "ganjbasoda": ["madhya pradesh"],
        "moga": ["punjab"],
        "proddatur": ["andhra pradesh"],
        "medinipur": ["west bengal"],
        "habra": ["west bengal"],
        "sasaram": ["bihar"],
        "hajipur": ["bihar"],
        "bhuj": ["gujarat"],
        "shivpuri": ["madhya pradesh"],
        "ranaghat": ["west bengal"],
        "shimla": ["himachal pradesh"],
        "tiruvannamalai": ["tamil nadu"],
        "kaithal": ["haryana"],
        "rajnandgaon": ["chhattisgarh"],
        "godhra": ["gujarat"],
        "hazaribag": ["jharkhand"],
        "bhimavaram": ["andhra pradesh"],
        "mandsaur": ["madhya pradesh"],
        "dibrugarh": ["assam"],
        "kolar": ["karnataka"],
        "bankura": ["west bengal"],
        "mandya": ["karnataka"],
        "dehri-on-sone": ["bihar"],
        "madanapalle": ["andhra pradesh"],
        "malerkotla": ["punjab"],
        "lalitpur": ["uttar pradesh"],
        "bettiah": ["bihar"],
        "pollachi": ["tamil nadu"],
        "khanna": ["punjab"],
        "neemuch": ["madhya pradesh"],
        "palwal": ["haryana"],
        "palanpur": ["gujarat"],
        "guntakal": ["andhra pradesh"],
        "nabadwip": ["west bengal"],
        "udupi": ["karnataka"],
        "jagdalpur": ["chhattisgarh"],
        "motihari": ["bihar"],
        "pilibhit": ["uttar pradesh"],
        "dimapur": ["nagaland"],
        "mohali": ["punjab"],
        "sadulpur": ["rajasthan"],
        "rajapalayam": ["tamil nadu"],
        "dharmavaram": ["andhra pradesh"],
        "kashipur": ["uttarakhand"],
        "sivakasi": ["tamil nadu"],
        "darjiling": ["west bengal"],
        "chikkamagaluru": ["karnataka"],
        "gudivada": ["andhra pradesh"],
        "baleshwar town": ["odisha"],
        "mancherial": ["telangana"],
        "srikakulam": ["andhra pradesh"],
        "adilabad": ["telangana"],
        "yavatmal": ["maharashtra"],
        "barnala": ["punjab"],
        "nagaon": ["assam"],
        "narasaraopet": ["andhra pradesh"],
        "raigarh": ["chhattisgarh"],
        "roorkee": ["uttarakhand"],
        "valsad": ["gujarat"],
        "ambikapur": ["chhattisgarh"],
        "giridih": ["jharkhand"],
        "chandausi": ["uttar pradesh"],
        "purulia": ["west bengal"],
        "patan": ["gujarat"],
        "bagaha": ["bihar"],
        "hardoi ": ["uttar pradesh"],
        "achalpur": ["maharashtra"],
        "osmanabad": ["maharashtra"],
        "deesa": ["gujarat"],
        "nandurbar": ["maharashtra"],
        "azamgarh": ["uttar pradesh"],
        "ramgarh": ["jharkhand"],
        "firozpur": ["punjab"],
        "baripada town": ["odisha"],
        "karwar": ["karnataka"],
        "siwan": ["bihar"],
        "rajampet": ["andhra pradesh"],
        "pudukkottai": ["tamil nadu"],
        "anantnag": ["jammu and kashmir"],
        "tadpatri": ["andhra pradesh"],
        "satara": ["maharashtra"],
        "bhadrak": ["odisha"],
        "kishanganj": ["bihar"],
        "suryapet": ["telangana"],
        "wardha": ["maharashtra"],
        "ranebennuru": ["karnataka"],
        "amreli": ["gujarat"],
        "neyveli (ts)": ["tamil nadu"],
        "jamalpur": ["bihar"],
        "marmagao": ["goa"],
        "udgir": ["maharashtra"],
        "tadepalligudem": ["andhra pradesh"],
        "nagapattinam": ["tamil nadu"],
        "buxar": ["bihar"],
        "aurangabad": ["maharashtra", "bihar"],
        "jehanabad": ["bihar"],
        "phagwara": ["punjab"],
        "khair": ["uttar pradesh"],
        "sawai madhopur": ["rajasthan"],
        "kapurthala": ["punjab"],
        "chilakaluripet": ["andhra pradesh"],
        "malappuram": ["kerala"],
        "rewari": ["haryana"],
        "nagaur": ["rajasthan"],
        "sultanpur": ["uttar pradesh"],
        "nagda": ["madhya pradesh"],
        "port blair": ["andaman and nicobar islands"],
        "lakhisarai": ["bihar"],
        "panaji": ["goa"],
        "tinsukia": ["assam"],
        "itarsi": ["madhya pradesh"],
        "kohima": ["nagaland"],
        "balangir": ["odisha"],
        "nawada": ["bihar"],
        "jharsuguda": ["odisha"],
        "jagtial": ["telangana"],
        "viluppuram": ["tamil nadu"],
        "amalner": ["maharashtra"],
        "zirakpur": ["punjab"],
        "tanda": ["uttar pradesh"],
        "tiruchengode": ["tamil nadu"],
        "nagina": ["uttar pradesh"],
        "yemmiganur": ["andhra pradesh"],
        "vaniyambadi": ["tamil nadu"],
        "sarni": ["madhya pradesh"],
        "theni allinagaram": ["tamil nadu"],
        "margao": ["goa"],
        "akot": ["maharashtra"],
        "sehore": ["madhya pradesh"],
        "mhow cantonment": ["madhya pradesh"],
        "kot kapura": ["punjab"],
        "makrana": ["rajasthan"],
        "pandharpur": ["maharashtra"],
        "miryalaguda": ["telangana"],
        "shamli": ["uttar pradesh"],
        "seoni": ["madhya pradesh"],
        "ranibennur": ["karnataka"],
        "kadiri": ["andhra pradesh"],
        "shrirampur": ["maharashtra"],
        "rudrapur": ["uttarakhand", "uttar pradesh"],
        "parli": ["maharashtra"],
        "najibabad": ["uttar pradesh"],
        "nirmal": ["telangana"],
        "udhagamandalam": ["tamil nadu"],
        "shikohabad": ["uttar pradesh"],
        "jhumri tilaiya": ["jharkhand"],
        "aruppukkottai": ["tamil nadu"],
        "ponnani": ["kerala"],
        "jamui": ["bihar"],
        "sitamarhi": ["bihar"],
        "chirala": ["andhra pradesh"],
        "anjar": ["gujarat"],
        "karaikal": ["puducherry"],
        "hansi": ["haryana"],
        "anakapalle": ["andhra pradesh"],
        "mahasamund": ["chhattisgarh"],
        "faridkot": ["punjab"],
        "saunda": ["jharkhand"],
        "dhoraji": ["gujarat"],
        "paramakudi": ["tamil nadu"],
        "balaghat": ["madhya pradesh"],
        "sujangarh": ["rajasthan"],
        "khambhat": ["gujarat"],
        "muktsar": ["punjab"],
        "rajpura": ["punjab"],
        "kavali": ["andhra pradesh"],
        "dhamtari": ["chhattisgarh"],
        "ashok nagar": ["madhya pradesh"],
        "sardarshahar": ["rajasthan"],
        "mahuva": ["gujarat"],
        "bargarh": ["odisha"],
        "kamareddy": ["telangana"],
        "sahibganj": ["jharkhand"],
        "kothagudem": ["telangana"],
        "ramanagaram": ["karnataka"],
        "gokak": ["karnataka"],
        "tikamgarh": ["madhya pradesh"],
        "araria": ["bihar"],
        "rishikesh": ["uttarakhand"],
        "shahdol": ["madhya pradesh"],
        "medininagar (daltonganj)": ["jharkhand"],
        "arakkonam": ["tamil nadu"],
        "washim": ["maharashtra"],
        "sangrur": ["punjab"],
        "bodhan": ["telangana"],
        "fazilka": ["punjab"],
        "palacole": ["andhra pradesh"],
        "keshod": ["gujarat"],
        "sullurpeta": ["andhra pradesh"],
        "wadhwan": ["gujarat"],
        "gurdaspur": ["punjab"],
        "vatakara": ["kerala"],
        "tura": ["meghalaya"],
        "narnaul": ["haryana"],
        "kharar": ["punjab"],
        "yadgir": ["karnataka"],
        "ambejogai": ["maharashtra"],
        "ankleshwar": ["gujarat"],
        "savarkundla": ["gujarat"],
        "paradip": ["odisha"],
        "virudhachalam": ["tamil nadu"],
        "kanhangad": ["kerala"],
        "kadi": ["gujarat"],
        "srivilliputhur": ["tamil nadu"],
        "gobindgarh": ["punjab"],
        "tindivanam": ["tamil nadu"],
        "taliparamba": ["kerala"],
        "manmad": ["maharashtra"],
        "tanuku": ["andhra pradesh"],
        "rayachoti": ["andhra pradesh"],
        "virudhunagar": ["tamil nadu"],
        "koyilandy": ["kerala"],
        "jorhat": ["assam"],
        "karur": ["tamil nadu"],
        "valparai": ["tamil nadu"],
        "srikalahasti": ["andhra pradesh"],
        "neyyattinkara": ["kerala"],
        "bapatla": ["andhra pradesh"],
        "fatehabad": ["haryana"],
        "malout": ["punjab"],
        "sankarankovil": ["tamil nadu"],
        "tenkasi": ["tamil nadu"],
        "ratnagiri": ["maharashtra"],
        "rabkavi banhatti": ["karnataka"],
        "sikandrabad": ["uttar pradesh"],
        "chaibasa": ["jharkhand"],
        "chirmiri": ["chhattisgarh"],
        "palwancha": ["telangana"],
        "bhawanipatna": ["odisha"],
        "kayamkulam": ["kerala"],
        "pithampur": ["madhya pradesh"],
        "nabha": ["punjab"],
        "shahabad, hardoi": ["uttar pradesh"],
        "dhenkanal": ["odisha"],
        "uran islampur": ["maharashtra"],
        "gopalganj": ["bihar"],
        "bongaigaon city": ["assam"],
        "palani": ["tamil nadu"],
        "pusad": ["maharashtra"],
        "sopore": ["jammu and kashmir"],
        "pilkhuwa": ["uttar pradesh"],
        "tarn taran": ["punjab"],
        "renukoot": ["uttar pradesh"],
        "mandamarri": ["telangana"],
        "shahabad": ["karnataka"],
        "barbil": ["odisha"],
        "koratla": ["telangana"],
        "madhubani": ["bihar"],
        "arambagh": ["west bengal"],
        "gohana": ["haryana"],
        "ladnu": ["rajasthan"],
        "pattukkottai": ["tamil nadu"],
        "sirsi": ["karnataka", "uttar pradesh"],
        "sircilla": ["telangana"],
        "tamluk": ["west bengal"],
        "jagraon": ["punjab"],
        "alipurdurban agglomerationr": ["west bengal"],
        "alirajpur": ["madhya pradesh"],
        "tandur": ["telangana"],
        "naidupet": ["andhra pradesh"],
        "tirupathur": ["tamil nadu"],
        "tohana": ["haryana"],
        "ratangarh": ["rajasthan"],
        "dhubri": ["assam"],
        "masaurhi": ["bihar"],
        "visnagar": ["gujarat"],
        "vrindavan": ["uttar pradesh"],
        "nagari": ["andhra pradesh"],
        "narwana": ["haryana"],
        "ramanathapuram": ["tamil nadu"],
        "ujhani": ["uttar pradesh"],
        "samastipur": ["bihar"],
        "laharpur": ["uttar pradesh"],
        "sangamner": ["maharashtra"],
        "nimbahera": ["rajasthan"],
        "siddipet": ["telangana"],
        "suri": ["west bengal"],
        "diphu": ["assam"],
        "jhargram": ["west bengal"],
        "shirpur-warwade": ["maharashtra"],
        "tilhar": ["uttar pradesh"],
        "sindhnur": ["karnataka"],
        "udumalaipettai": ["tamil nadu"],
        "malkapur": ["maharashtra"],
        "wanaparthy": ["telangana"],
        "gudur": ["andhra pradesh"],
        "kendujhar": ["odisha"],
        "mandla": ["madhya pradesh"],
        "mandi": ["himachal pradesh"],
        "nedumangad": ["kerala"],
        "north lakhimpur": ["assam"],
        "vinukonda": ["andhra pradesh"],
        "tiptur": ["karnataka"],
        "gobichettipalayam": ["tamil nadu"],
        "sunabeda": ["odisha"],
        "wani": ["maharashtra"],
        "upleta": ["gujarat"],
        "narasapuram": ["andhra pradesh"],
        "nuzvid": ["andhra pradesh"],
        "tezpur": ["assam"],
        "una": ["gujarat"],
        "markapur": ["andhra pradesh"],
        "sheopur": ["madhya pradesh"],
        "thiruvarur": ["tamil nadu"],
        "sidhpur": ["gujarat"],
        "sahaswan": ["uttar pradesh"],
        "suratgarh": ["rajasthan"],
        "shajapur": ["madhya pradesh"],
        "rayagada": ["odisha"],
        "lonavla": ["maharashtra"],
        "ponnur": ["andhra pradesh"],
        "kagaznagar": ["telangana"],
        "gadwal": ["telangana"],
        "bhatapara": ["chhattisgarh"],
        "kandukur": ["andhra pradesh"],
        "sangareddy": ["telangana"],
        "unjha": ["gujarat"],
        "lunglei": ["mizoram"],
        "karimganj": ["assam"],
        "kannur": ["kerala"],
        "bobbili": ["andhra pradesh"],
        "mokameh": ["bihar"],
        "talegaon dabhade": ["maharashtra"],
        "anjangaon": ["maharashtra"],
        "sunam": ["punjab"],
        "gangarampur": ["west bengal"],
        "thiruvallur": ["tamil nadu"],
        "tirur": ["kerala"],
        "rath": ["uttar pradesh"],
        "jatani": ["odisha"],
        "viramgam": ["gujarat"],
        "rajsamand": ["rajasthan"],
        "yanam": ["puducherry"],
        "kottayam": ["kerala"],
        "panruti": ["tamil nadu"],
        "dhuri": ["punjab"],
        "namakkal": ["tamil nadu"],
        "kasaragod": ["kerala"],
        "modasa": ["gujarat"],
        "rayadurg": ["andhra pradesh"],
        "supaul": ["bihar"],
        "kunnamkulam": ["kerala"],
        "umred": ["maharashtra"],
        "bellampalle": ["telangana"],
        "sibsagar": ["assam"],
        "mandi dabwali": ["haryana"],
        "ottappalam": ["kerala"],
        "dumraon": ["bihar"],
        "samalkot": ["andhra pradesh"],
        "jaggaiahpet": ["andhra pradesh"],
        "goalpara": ["assam"],
        "tuni": ["andhra pradesh"],
        "lachhmangarh": ["rajasthan"],
        "bhongir": ["telangana"],
        "amalapuram": ["andhra pradesh"],
        "firozpur cantt.": ["punjab"],
        "vikarabad": ["telangana"],
        "thiruvalla": ["kerala"],
        "sherkot": ["uttar pradesh"],
        "palghar": ["maharashtra"],
        "shegaon": ["maharashtra"],
        "jangaon": ["telangana"],
        "bheemunipatnam": ["andhra pradesh"],
        "panna": ["madhya pradesh"],
        "thodupuzha": ["kerala"],
        "kathurban agglomeration": ["jammu and kashmir"],
        "palitana": ["gujarat"],
        "arwal": ["bihar"],
        "venkatagiri": ["andhra pradesh"],
        "kalpi": ["uttar pradesh"],
        "rajgarh (churu)": ["rajasthan"],
        "sattenapalle": ["andhra pradesh"],
        "arsikere": ["karnataka"],
        "ozar": ["maharashtra"],
        "thirumangalam": ["tamil nadu"],
        "petlad": ["gujarat"],
        "nasirabad": ["rajasthan"],
        "phaltan": ["maharashtra"],
        "rampurhat": ["west bengal"],
        "nanjangud": ["karnataka"],
        "forbesganj": ["bihar"],
        "tundla": ["uttar pradesh"],
        "bhaburban agglomeration": ["bihar"],
        "sagara": ["karnataka"],
        "pithapuram": ["andhra pradesh"],
        "sira": ["karnataka"],
        "bhadrachalam": ["telangana"],
        "charkhi dadri": ["haryana"],
        "chatra": ["jharkhand"],
        "palasa kasibugga": ["andhra pradesh"],
        "nohar": ["rajasthan"],
        "yevla": ["maharashtra"],
        "sirhind fatehgarh sahib": ["punjab"],
        "bhainsa": ["telangana"],
        "parvathipuram": ["andhra pradesh"],
        "shahade": ["maharashtra"],
        "chalakudy": ["kerala"],
        "narkatiaganj": ["bihar"],
        "kapadvanj": ["gujarat"],
        "macherla": ["andhra pradesh"],
        "raghogarh-vijaypur": ["madhya pradesh"],
        "rupnagar": ["punjab"],
        "naugachhia": ["bihar"],
        "sendhwa": ["madhya pradesh"],
        "byasanagar": ["odisha"],
        "sandila": ["uttar pradesh"],
        "gooty": ["andhra pradesh"],
        "salur": ["andhra pradesh"],
        "nanpara": ["uttar pradesh"],
        "sardhana": ["uttar pradesh"],
        "vita": ["maharashtra"],
        "gumia": ["jharkhand"],
        "jalandhar cantt.": ["punjab"],
        "nehtaur": ["uttar pradesh"],
        "changanassery": ["kerala"],
        "mandapeta": ["andhra pradesh"],
        "dumka": ["jharkhand"],
        "seohara": ["uttar pradesh"],
        "umarkhed": ["maharashtra"],
        "madhupur": ["jharkhand"],
        "vikramasingapuram": ["tamil nadu"],
        "punalur": ["kerala"],
        "kendrapara": ["odisha"],
        "sihor": ["gujarat"],
        "nellikuppam": ["tamil nadu"],
        "samana": ["punjab"],
        "warora": ["maharashtra"],
        "nilambur": ["kerala"],
        "rasipuram": ["tamil nadu"],
        "ramnagar": ["uttarakhand", "bihar"],
        "jammalamadugu": ["andhra pradesh"],
        "nawanshahr": ["punjab"],
        "thoubal": ["manipur"],
        "athni": ["karnataka"],
        "cherthala": ["kerala"],
        "sidhi": ["madhya pradesh"],
        "farooqnagar": ["telangana"],
        "peddapuram": ["andhra pradesh"],
        "chirkunda": ["jharkhand"],
        "pachora": ["maharashtra"],
        "madhepura": ["bihar"],
        "pithoragarh": ["uttarakhand"],
        "tumsar": ["maharashtra"],
        "phalodi": ["rajasthan"],
        "tiruttani": ["tamil nadu"],
        "rampura phul": ["punjab"],
        "perinthalmanna": ["kerala"],
        "padrauna": ["uttar pradesh"],
        "pipariya": ["madhya pradesh"],
        "dalli-rajhara": ["chhattisgarh"],
        "punganur": ["andhra pradesh"],
        "mattannur": ["kerala"],
        "mathura": ["uttar pradesh"],
        "thakurdwara": ["uttar pradesh"],
        "nandivaram-guduvancheri": ["tamil nadu"],
        "mulbagal": ["karnataka"],
        "manjlegaon": ["maharashtra"],
        "wankaner": ["gujarat"],
        "sillod": ["maharashtra"],
        "nidadavole": ["andhra pradesh"],
        "surapura": ["karnataka"],
        "rajagangapur": ["odisha"],
        "sheikhpura": ["bihar"],
        "parlakhemundi": ["odisha"],
        "kalimpong": ["west bengal"],
        "siruguppa": ["karnataka"],
        "arvi": ["maharashtra"],
        "limbdi": ["gujarat"],
        "barpeta": ["assam"],
        "manglaur": ["uttarakhand"],
        "repalle": ["andhra pradesh"],
        "mudhol": ["karnataka"],
        "shujalpur": ["madhya pradesh"],
        "mandvi": ["gujarat"],
        "thangadh": ["gujarat"],
        "sironj": ["madhya pradesh"],
        "nandura": ["maharashtra"],
        "shoranur": ["kerala"],
        "nathdwara": ["rajasthan"],
        "periyakulam": ["tamil nadu"],
        "sultanganj": ["bihar"],
        "medak": ["telangana"],
        "narayanpet": ["telangana"],
        "raxaul bazar": ["bihar"],
        "rajauri": ["jammu and kashmir"],
        "pernampattu": ["tamil nadu"],
        "nainital": ["uttarakhand"],
        "ramachandrapuram": ["andhra pradesh"],
        "vaijapur": ["maharashtra"],
        "nangal": ["punjab"],
        "sidlaghatta": ["karnataka"],
        "punch": ["jammu and kashmir"],
        "pandhurna": ["madhya pradesh"],
        "wadgaon road": ["maharashtra"],
        "talcher": ["odisha"],
        "varkala": ["kerala"],
        "pilani": ["rajasthan"],
        "nowgong": ["madhya pradesh"],
        "naila janjgir": ["chhattisgarh"],
        "mapusa": ["goa"],
        "vellakoil": ["tamil nadu"],
        "merta city": ["rajasthan"],
        "sivaganga": ["tamil nadu"],
        "mandideep": ["madhya pradesh"],
        "sailu": ["maharashtra"],
        "vyara": ["gujarat"],
        "kovvur": ["andhra pradesh"],
        "vadalur": ["tamil nadu"],
        "nawabganj": ["uttar pradesh"],
        "padra": ["gujarat"],
        "sainthia": ["west bengal"],
        "siana": ["uttar pradesh"],
        "shahpur": ["karnataka"],
        "sojat": ["rajasthan"],
        "noorpur": ["uttar pradesh"],
        "paravoor": ["kerala"],
        "murtijapur": ["maharashtra"],
        "sundargarh": ["odisha"],
        "taki": ["west bengal"],
        "saundatti-yellamma": ["karnataka"],
        "pathanamthitta": ["kerala"],
        "wadi": ["karnataka"],
        "rameshwaram": ["tamil nadu"],
        "tasgaon": ["maharashtra"],
        "sikandra rao": ["uttar pradesh"],
        "sihora": ["madhya pradesh"],
        "tiruvethipuram": ["tamil nadu"],
        "tiruvuru": ["andhra pradesh"],
        "mehkar": ["maharashtra"],
        "peringathur": ["kerala"],
        "perambalur": ["tamil nadu"],
        "manvi": ["karnataka"],
        "zunheboto": ["nagaland"],
        "mahnar bazar": ["bihar"],
        "attingal": ["kerala"],
        "shahbad": ["haryana"],
        "puranpur": ["uttar pradesh"],
        "nelamangala": ["karnataka"],
        "nakodar": ["punjab"],
        "lunawada": ["gujarat"],
        "murshidabad": ["west bengal"],
        "mahe": ["puducherry"],
        "lanka": ["assam"],
        "rudauli": ["uttar pradesh"],
        "tuensang": ["nagaland"],
        "lakshmeshwar": ["karnataka"],
        "zira": ["punjab"],
        "yawal": ["maharashtra"],
        "thana bhawan": ["uttar pradesh"],
        "ramdurg": ["karnataka"],
        "pulgaon": ["maharashtra"],
        "sadasivpet": ["telangana"],
        "nargund": ["karnataka"],
        "neem-ka-thana": ["rajasthan"],
        "memari": ["west bengal"],
        "nilanga": ["maharashtra"],
        "naharlagun": ["arunachal pradesh"],
        "pakaur": ["jharkhand"],
        "wai": ["maharashtra"],
        "tarikere": ["karnataka"],
        "malavalli": ["karnataka"],
        "raisen": ["madhya pradesh"],
        "lahar": ["madhya pradesh"],
        "uravakonda": ["andhra pradesh"],
        "savanur": ["karnataka"],
        "sirohi": ["rajasthan"],
        "udhampur": ["jammu and kashmir"],
        "umarga": ["maharashtra"],
        "lingsugur": ["karnataka"],
        "usilampatti": ["tamil nadu"],
        "palia kalan": ["uttar pradesh"],
        "wokha": ["nagaland"],
        "rajpipla": ["gujarat"],
        "vijayapura": ["karnataka"],
        "rawatbhata": ["rajasthan"],
        "sangaria": ["rajasthan"],
        "paithan": ["maharashtra"],
        "rahuri": ["maharashtra"],
        "patti": ["punjab"],
        "zaidpur": ["uttar pradesh"],
        "lalsot": ["rajasthan"],
        "maihar": ["madhya pradesh"],
        "vedaranyam": ["tamil nadu"],
        "nawapur": ["maharashtra"],
        "solan": ["himachal pradesh"],
        "vapi": ["gujarat"],
        "sanawad": ["madhya pradesh"],
        "warisaliganj": ["bihar"],
        "revelganj": ["bihar"],
        "sabalgarh": ["madhya pradesh"],
        "tuljapur": ["maharashtra"],
        "simdega": ["jharkhand"],
        "musabani": ["jharkhand"],
        "kodungallur": ["kerala"],
        "phulabani": ["odisha"],
        "umreth": ["gujarat"],
        "narsipatnam": ["andhra pradesh"],
        "nautanwa": ["uttar pradesh"],
        "rajgir": ["bihar"],
        "yellandu": ["telangana"],
        "sathyamangalam": ["tamil nadu"],
        "pilibanga": ["rajasthan"],
        "morshi": ["maharashtra"],
        "pehowa": ["haryana"],
        "sonepur": ["bihar"],
        "pappinisseri": ["kerala"],
        "zamania": ["uttar pradesh"],
        "mihijam": ["jharkhand"],
        "purna": ["maharashtra"],
        "puliyankudi": ["tamil nadu"],
        "shikarpur, bulandshahr": ["uttar pradesh"],
        "umaria": ["madhya pradesh"],
        "porsa": ["madhya pradesh"],
        "naugawan sadat": ["uttar pradesh"],
        "fatehpur sikri": ["uttar pradesh"],
        "manuguru": ["telangana"],
        "udaipur": ["tripura", "rajasthan"],
        "pipar city": ["rajasthan"],
        "pattamundai": ["odisha"],
        "nanjikottai": ["tamil nadu"],
        "taranagar": ["rajasthan"],
        "yerraguntla": ["andhra pradesh"],
        "satana": ["maharashtra"],
        "sherghati": ["bihar"],
        "sankeshwara": ["karnataka"],
        "madikeri": ["karnataka"],
        "thuraiyur": ["tamil nadu"],
        "sanand": ["gujarat"],
        "rajula": ["gujarat"],
        "kyathampalle": ["telangana"],
        "shahabad, rampur": ["uttar pradesh"],
        "tilda newra": ["chhattisgarh"],
        "narsinghgarh": ["madhya pradesh"],
        "chittur-thathamangalam": ["kerala"],
        "malaj khand": ["madhya pradesh"],
        "sarangpur": ["madhya pradesh"],
        "robertsganj": ["uttar pradesh"],
        "sirkali": ["tamil nadu"],
        "radhanpur": ["gujarat"],
        "tiruchendur": ["tamil nadu"],
        "utraula": ["uttar pradesh"],
        "patratu": ["jharkhand"],
        "vijainagar, ajmer": ["rajasthan"],
        "periyasemur": ["tamil nadu"],
        "pathri": ["maharashtra"],
        "sadabad": ["uttar pradesh"],
        "talikota": ["karnataka"],
        "sinnar": ["maharashtra"],
        "mungeli": ["chhattisgarh"],
        "sedam": ["karnataka"],
        "shikaripur": ["karnataka"],
        "sattur": ["tamil nadu"],
        "sugauli": ["bihar"],
        "lumding": ["assam"],
        "vandavasi": ["tamil nadu"],
        "titlagarh": ["odisha"],
        "uchgaon": ["maharashtra"],
        "mokokchung": ["nagaland"],
        "paschim punropara": ["west bengal"],
        "sagwara": ["rajasthan"],
        "ramganj mandi": ["rajasthan"],
        "tarakeswar": ["west bengal"],
        "mahalingapura": ["karnataka"],
        "dharmanagar": ["tripura"],
        "mahemdabad": ["gujarat"],
        "manendragarh": ["chhattisgarh"],
        "uran": ["maharashtra"],
        "tharamangalam": ["tamil nadu"],
        "tirukkoyilur": ["tamil nadu"],
        "pen": ["maharashtra"],
        "makhdumpur": ["bihar"],
        "maner": ["bihar"],
        "oddanchatram": ["tamil nadu"],
        "palladam": ["tamil nadu"],
        "mundi": ["madhya pradesh"],
        "nabarangapur": ["odisha"],
        "mudalagi": ["karnataka"],
        "samalkha": ["haryana"],
        "nepanagar": ["madhya pradesh"],
        "karjat": ["maharashtra"],
        "ranavav": ["gujarat"],
        "pedana": ["andhra pradesh"],
        "pinjore": ["haryana"],
        "lakheri": ["rajasthan"],
        "pasan": ["madhya pradesh"],
        "puttur": ["andhra pradesh", "karnataka"],
        "vadakkuvalliyur": ["tamil nadu"],
        "tirukalukundram": ["tamil nadu"],
        "mahidpur": ["madhya pradesh"],
        "mussoorie": ["uttarakhand"],
        "muvattupuzha": ["kerala"],
        "rasra": ["uttar pradesh"],
        "udaipurwati": ["rajasthan"],
        "manwath": ["maharashtra"],
        "adoor": ["kerala"],
        "uthamapalayam": ["tamil nadu"],
        "partur": ["maharashtra"],
        "nahan": ["himachal pradesh"],
        "ladwa": ["haryana"],
        "mankachar": ["assam"],
        "nongstoin": ["meghalaya"],
        "losal": ["rajasthan"],
        "sri madhopur": ["rajasthan"],
        "ramngarh": ["rajasthan"],
        "mavelikkara": ["kerala"],
        "rawatsar": ["rajasthan"],
        "rajakhera": ["rajasthan"],
        "lar": ["uttar pradesh"],
        "lal gopalganj nindaura": ["uttar pradesh"],
        "muddebihal": ["karnataka"],
        "sirsaganj": ["uttar pradesh"],
        "shahpura": ["rajasthan"],
        "surandai": ["tamil nadu"],
        "sangole": ["maharashtra"],
        "pavagada": ["karnataka"],
        "tharad": ["gujarat"],
        "mansa": ["gujarat", "punjab"],
        "umbergaon": ["gujarat"],
        "mavoor": ["kerala"],
        "nalbari": ["assam"],
        "talaja": ["gujarat"],
        "malur": ["karnataka"],
        "mangrulpir": ["maharashtra"],
        "soro": ["odisha"],
        "vadnagar": ["gujarat"],
        "raisinghnagar": ["rajasthan"],
        "sindhagi": ["karnataka"],
        "sanduru": ["karnataka"],
        "sohna": ["haryana"],
        "manavadar": ["gujarat"],
        "pihani": ["uttar pradesh"],
        "safidon": ["haryana"],
        "risod": ["maharashtra"],
        "rosera": ["bihar"],
        "sankari": ["tamil nadu"],
        "malpura": ["rajasthan"],
        "sonamukhi": ["west bengal"],
        "shamsabad, agra": ["uttar pradesh"],
        "nokha": ["bihar", "rajasthan"],
        "pandurban agglomeration": ["west bengal"],
        "mainaguri": ["west bengal"],
        "afzalpur": ["karnataka"],
        "shirur": ["maharashtra"],
        "salaya": ["gujarat"],
        "shenkottai": ["tamil nadu"],
        "pratapgarh": ["tripura", "rajasthan"],
        "vadipatti": ["tamil nadu"],
        "nagarkurnool": ["telangana"],
        "savner": ["maharashtra"],
        "sasvad": ["maharashtra"],
        "soron": ["uttar pradesh"],
        "sholingur": ["tamil nadu"],
        "pandharkaoda": ["maharashtra"],
        "perumbavoor": ["kerala"],
        "maddur": ["karnataka"],
        "nadbai": ["rajasthan"],
        "talode": ["maharashtra"],
        "shrigonda": ["maharashtra"],
        "madhugiri": ["karnataka"],
        "tekkalakote": ["karnataka"],
        "seoni-malwa": ["madhya pradesh"],
        "shirdi": ["maharashtra"],
        "surban agglomerationr": ["uttar pradesh"],
        "terdal": ["karnataka"],
        "raver": ["maharashtra"],
        "taraori": ["haryana"],
        "mukhed": ["maharashtra"],
        "manachanallur": ["tamil nadu"],
        "rehli": ["madhya pradesh"],
        "sanchore": ["rajasthan"],
        "rajura": ["maharashtra"],
        "piro": ["bihar"],
        "mudabidri": ["karnataka"],
        "vadgaon kasba": ["maharashtra"],
        "nagar": ["rajasthan"],
        "vijapur": ["gujarat"],
        "viswanatham": ["tamil nadu"],
        "polur": ["tamil nadu"],
        "panagudi": ["tamil nadu"],
        "manawar": ["madhya pradesh"],
        "tehri": ["uttarakhand"],
        "samdhan": ["uttar pradesh"],
        "pardi": ["gujarat"],
        "rahatgarh": ["madhya pradesh"],
        "panagar": ["madhya pradesh"],
        "uthiramerur": ["tamil nadu"],
        "tirora": ["maharashtra"],
        "rangia": ["assam"],
        "sahjanwa": ["uttar pradesh"],
        "wara seoni": ["madhya pradesh"],
        "magadi": ["karnataka"],
        "rajgarh (alwar)": ["rajasthan"],
        "rafiganj": ["bihar"],
        "tarana": ["madhya pradesh"],
        "rampur maniharan": ["uttar pradesh"],
        "sheoganj": ["rajasthan"],
        "raikot": ["punjab"],
        "pauri": ["uttarakhand"],
        "sumerpur": ["uttar pradesh", "rajasthan"],
        "navalgund": ["karnataka"],
        "shahganj": ["uttar pradesh"],
        "marhaura": ["bihar"],
        "tulsipur": ["uttar pradesh"],
        "sadri": ["rajasthan"],
        "thiruthuraipoondi": ["tamil nadu"],
        "shiggaon": ["karnataka"],
        "pallapatti": ["tamil nadu"],
        "mahendragarh": ["haryana"],
        "sausar": ["madhya pradesh"],
        "ponneri": ["tamil nadu"],
        "mahad": ["maharashtra"],
        "lohardaga": ["jharkhand"],
        "tirwaganj": ["uttar pradesh"],
        "margherita": ["assam"],
        "sundarnagar": ["himachal pradesh"],
        "rajgarh": ["madhya pradesh"],
        "mangaldoi": ["assam"],
        "renigunta": ["andhra pradesh"],
        "longowal": ["punjab"],
        "ratia": ["haryana"],
        "lalgudi": ["tamil nadu"],
        "shrirangapattana": ["karnataka"],
        "niwari": ["madhya pradesh"],
        "natham": ["tamil nadu"],
        "unnamalaikadai": ["tamil nadu"],
        "purqurban agglomerationzi": ["uttar pradesh"],
        "shamsabad, farrukhabad": ["uttar pradesh"],
        "mirganj": ["bihar"],
        "todaraisingh": ["rajasthan"],
        "warhapur": ["uttar pradesh"],
        "rajam": ["andhra pradesh"],
        "urmar tanda": ["punjab"],
        "lonar": ["maharashtra"],
        "powayan": ["uttar pradesh"],
        "p.n.patti": ["tamil nadu"],
        "palampur": ["himachal pradesh"],
        "srisailam project (right flank colony) township": ["andhra pradesh"],
        "sindagi": ["karnataka"],
        "sandi": ["uttar pradesh"],
        "vaikom": ["kerala"],
        "malda": ["west bengal"],
        "tharangambadi": ["tamil nadu"],
        "sakaleshapura": ["karnataka"],
        "malkangiri": ["odisha"],
        "rapar": ["gujarat"],
        "mauganj": ["madhya pradesh"],
        "todabhim": ["rajasthan"],
        "srinivaspur": ["karnataka"],
        "murliganj": ["bihar"],
        "reengus": ["rajasthan"],
        "sawantwadi": ["maharashtra"],
        "tittakudi": ["tamil nadu"],
        "lilong": ["manipur"],
        "rajaldesar": ["rajasthan"],
        "pathardi": ["maharashtra"],
        "achhnera": ["uttar pradesh"],
        "pacode": ["tamil nadu"],
        "naraura": ["uttar pradesh"],
        "nakur": ["uttar pradesh"],
        "palai": ["kerala"],
        "morinda, india": ["punjab"],
        "manasa": ["madhya pradesh"],
        "nainpur": ["madhya pradesh"],
        "sahaspur": ["uttar pradesh"],
        "pauni": ["maharashtra"],
        "prithvipur": ["madhya pradesh"],
        "ramtek": ["maharashtra"],
        "silapathar": ["assam"],
        "songadh": ["gujarat"],
        "safipur": ["uttar pradesh"],
        "sohagpur": ["madhya pradesh"],
        "mul": ["maharashtra"],
        "sadulshahar": ["rajasthan"],
        "phillaur": ["punjab"],
        "sambhar": ["rajasthan"],
        "prantij": ["rajasthan"],
        "nagla": ["uttarakhand"],
        "pattran": ["punjab"],
        "mount abu": ["rajasthan"],
        "reoti": ["uttar pradesh"],
        "tenu dam-cum-kathhara": ["jharkhand"],
        "panchla": ["west bengal"],
        "sitarganj": ["uttarakhand"],
        "pasighat": ["arunachal pradesh"],
        "motipur": ["bihar"],
        "o' valley": ["tamil nadu"],
        "raghunathpur": ["west bengal"],
        "suriyampalayam": ["tamil nadu"],
        "qadian": ["punjab"],
        "rairangpur": ["odisha"],
        "silvassa": ["dadra and nagar haveli"],
        "nowrozabad (khodargama)": ["madhya pradesh"],
        "mangrol": ["rajasthan", "gujarat"],
        "soyagaon": ["maharashtra"],
        "sujanpur": ["punjab"],
        "manihari": ["bihar"],
        "sikanderpur": ["uttar pradesh"],
        "mangalvedhe": ["maharashtra"],
        "phulera": ["rajasthan"],
        "ron": ["karnataka"],
        "sholavandan": ["tamil nadu"],
        "saidpur": ["uttar pradesh"],
        "shamgarh": ["madhya pradesh"],
        "thammampatti": ["tamil nadu"],
        "maharajpur": ["madhya pradesh"],
        "multai": ["madhya pradesh"],
        "mukerian": ["punjab"],
        "purwa": ["uttar pradesh"],
        "sheohar": ["bihar"],
        "namagiripettai": ["tamil nadu"],
        "parasi": ["uttar pradesh"],
        "lathi": ["gujarat"],
        "lalganj": ["uttar pradesh", "bihar"],
        "narkhed": ["maharashtra"],
        "mathabhanga": ["west bengal"],
        "shendurjana": ["maharashtra"],
        "peravurani": ["tamil nadu"],
        "mariani": ["assam"],
        "phulpur": ["uttar pradesh"],
        "rania": ["haryana"],
        "pali": ["madhya pradesh", "rajasthan"],
        "pachore": ["madhya pradesh"],
        "parangipettai": ["tamil nadu"],
        "pudupattinam": ["tamil nadu"],
        "panniyannur": ["kerala"],
        "maharajganj": ["bihar"],
        "rau": ["madhya pradesh"],
        "monoharpur": ["west bengal"],
        "mandawa": ["rajasthan"],
        "marigaon": ["assam"],
        "pallikonda": ["tamil nadu"],
        "pindwara": ["rajasthan"],
        "shishgarh": ["uttar pradesh"],
        "patur": ["maharashtra"],
        "mayang imphal": ["manipur"],
        "mhowgaon": ["madhya pradesh"],
        "guruvayoor": ["kerala"],
        "mhaswad": ["maharashtra"],
        "sahawar": ["uttar pradesh"],
        "sivagiri": ["tamil nadu"],
        "mundargi": ["karnataka"],
        "punjaipugalur": ["tamil nadu"],
        "kailasahar": ["tripura"],
        "samthar": ["uttar pradesh"],
        "sakti": ["chhattisgarh"],
        "sadalagi": ["karnataka"],
        "silao": ["bihar"],
        "mandalgarh": ["rajasthan"],
        "loha": ["maharashtra"],
        "pukhrayan": ["uttar pradesh"],
        "padmanabhapuram": ["tamil nadu"],
        "belonia": ["tripura"],
        "saiha": ["mizoram"],
        "srirampore": ["west bengal"],
        "talwara": ["punjab"],
        "puthuppally": ["kerala"],
        "khowai": ["tripura"],
        "vijaypur": ["madhya pradesh"],
        "takhatgarh": ["rajasthan"],
        "thirupuvanam": ["tamil nadu"],
        "adra": ["west bengal"],
        "piriyapatna": ["karnataka"],
        "obra": ["uttar pradesh"],
        "adalaj": ["gujarat"],
        "nandgaon": ["maharashtra"],
        "barh": ["bihar"],
        "panamattom": ["kerala"],
        "niwai": ["uttar pradesh"],
        "bageshwar": ["uttarakhand"],
        "tarbha": ["odisha"],
        "adyar": ["karnataka"],
        "warud": ["maharashtra"],
        "asarganj": ["bihar"],
        "sarsod": ["haryana"],
    }
    return city_state_mapping.get(city.lower(), [])
