from typing import List


def get_states_for_city(city: str) -> List[str]:
    city_state_mapping = {
        "mumbai": ["maharashtra"],
        "delhi": ["delhi", "delhi_(nct)"],
        "bengaluru": ["karnataka"],
        "ahmedabad": ["gujarat"],
        "hyderabad": ["telangana"],
        "chennai": ["tamil_nadu", "tamil nadu"],
        "kolkata": ["west_bengal", "west bengal"],
        "pune": ["maharashtra"],
        "jaipur": ["rajasthan"],
        "surat": ["gujarat"],
        "lucknow": ["uttar_pradesh", "uttar pradesh"],
        "kanpur": ["uttar_pradesh", "uttar pradesh"],
        "nagpur": ["maharashtra"],
        "patna": ["bihar"],
        "indore": ["madhya_pradesh", "madhya pradesh"],
        "thane": ["maharashtra"],
        "bhopal": ["madhya_pradesh", "madhya pradesh"],
        "visakhapatnam": ["andhra_pradesh", "andhra pradesh"],
        "vadodara": ["gujarat"],
        "firozabad": ["uttar_pradesh", "uttar pradesh"],
        "ludhiana": ["punjab"],
        "rajkot": ["gujarat"],
        "agra": ["uttar_pradesh", "uttar pradesh"],
        "siliguri": ["west_bengal", "west bengal"],
        "nashik": ["maharashtra"],
        "faridabad": ["haryana"],
        "patiala": ["punjab"],
        "meerut": ["uttar_pradesh", "uttar pradesh"],
        "kalyan-dombivali": ["maharashtra"],
        "vasai-virar": ["maharashtra"],
        "vasai": ["maharashtra"],
        "virar": ["maharashtra"],
        "varanasi": ["uttar_pradesh", "uttar pradesh"],
        "srinagar": ["jammu_and_kashmir", "jammu and kashmir", "uttarakhand"],
        "dhanbad": ["jharkhand"],
        "jodhpur": ["rajasthan"],
        "amritsar": ["punjab"],
        "raipur": ["chhattisgarh"],
        "allahabad": ["uttar_pradesh", "uttar pradesh"],
        "prayagraj": ["uttar_pradesh", "uttar pradesh"],
        "coimbatore": ["tamil_nadu", "tamil nadu"],
        "jabalpur": ["madhya_pradesh", "madhya pradesh"],
        "gwalior": ["madhya_pradesh", "madhya pradesh"],
        "vijayawada": ["andhra_pradesh", "andhra pradesh"],
        "madurai": ["tamil_nadu", "tamil nadu"],
        "guwahati": ["assam"],
        "chandigarh": ["chandigarh"],
        "hubli-dharwad": ["karnataka"],
        "hubli": ["karnataka"],
        "hubballi": ["karnataka"],
        "amroha": ["uttar_pradesh", "uttar pradesh"],
        "moradabad": ["uttar_pradesh", "uttar pradesh"],
        "gurgaon": ["haryana"],
        "gurugram": ["haryana"],
        "aligarh": ["uttar_pradesh", "uttar pradesh"],
        "solapur": ["maharashtra"],
        "ranchi": ["jharkhand"],
        "jalandhar": ["punjab"],
        "tiruchirappalli": ["tamil_nadu", "tamil nadu"],
        "bhubaneswar": ["odisha"],
        "salem": ["tamil_nadu", "tamil nadu"],
        "warangal": ["telangana"],
        "mira-bhayandar": ["maharashtra"],
        "thiruvananthapuram": ["kerala"],
        "bhiwandi": ["maharashtra"],
        "saharanpur": ["uttar_pradesh", "uttar pradesh"],
        "guntur": ["andhra_pradesh", "andhra pradesh"],
        "amravati": ["maharashtra"],
        "bikaner": ["rajasthan"],
        "noida": ["uttar_pradesh", "uttar pradesh"],
        "jamshedpur": ["jharkhand"],
        "bhilai nagar": ["chhattisgarh"],
        "cuttack": ["odisha"],
        "kochi": ["kerala"],
        "bhavnagar": ["gujarat"],
        "dehradun": ["uttarakhand"],
        "asansol": ["west_bengal", "west bengal"],
        "nanded-waghala": ["maharashtra"],
        "ajmer": ["rajasthan"],
        "jamnagar": ["gujarat"],
        "ujjain": ["madhya_pradesh", "madhya pradesh"],
        "sangli": ["maharashtra"],
        "loni": ["uttar_pradesh", "uttar pradesh"],
        "jhansi": ["uttar_pradesh", "uttar pradesh"],
        "pondicherry": ["puducherry"],
        "nellore": ["andhra_pradesh", "andhra pradesh"],
        "jammu": ["jammu_and_kashmir", "jammu and kashmir"],
        "belagavi": ["karnataka"],
        "raurkela": ["odisha"],
        "mangaluru": ["karnataka"],
        "tirunelveli": ["tamil_nadu", "tamil nadu"],
        "malegaon": ["maharashtra"],
        "gaya": ["bihar"],
        "tiruppur": ["tamil_nadu", "tamil nadu"],
        "davanagere": ["karnataka"],
        "kozhikode": ["kerala"],
        "akola": ["maharashtra"],
        "kurnool": ["andhra_pradesh", "andhra pradesh"],
        "bokaro steel city": ["jharkhand"],
        "rajahmundry": ["andhra_pradesh", "andhra pradesh"],
        "ballari": ["karnataka"],
        "bellary": ["karnataka"],
        "agartala": ["tripura"],
        "bhagalpur": ["bihar"],
        "latur": ["maharashtra"],
        "dhule": ["maharashtra"],
        "korba": ["chhattisgarh"],
        "bhilwara": ["rajasthan"],
        "brahmapur": ["odisha"],
        "mysore": ["karnataka"],
        "mysuru": ["karnataka"],
        "muzaffarpur": ["bihar"],
        "ahmednagar": ["maharashtra"],
        "kollam": ["kerala"],
        "raghunathganj": ["west_bengal", "west bengal"],
        "bilaspur": ["chhattisgarh"],
        "shahjahanpur": ["uttar_pradesh", "uttar pradesh"],
        "thrissur": ["kerala"],
        "alwar": ["rajasthan"],
        "kakinada": ["andhra_pradesh", "andhra pradesh"],
        "nizamabad": ["telangana"],
        "sagar": ["madhya_pradesh", "madhya pradesh"],
        "tumkur": ["karnataka"],
        "tumakuru": ["karnataka"],
        "hisar": ["haryana"],
        "rohtak": ["haryana"],
        "panipat": ["haryana"],
        "darbhanga": ["bihar"],
        "kharagpur": ["west_bengal", "west bengal"],
        "aizawl": ["mizoram"],
        "ichalkaranji": ["maharashtra"],
        "tirupati": ["andhra_pradesh", "andhra pradesh"],
        "karnal": ["haryana"],
        "bathinda": ["punjab"],
        "rampur": ["uttar_pradesh", "uttar pradesh"],
        "shivamogga": ["karnataka"],
        "ratlam": ["madhya_pradesh", "madhya pradesh"],
        "modinagar": ["uttar_pradesh", "uttar pradesh"],
        "durg": ["chhattisgarh"],
        "shillong": ["meghalaya"],
        "imphal": ["manipur"],
        "hapur": ["uttar_pradesh", "uttar pradesh"],
        "ranipet": ["tamil_nadu", "tamil nadu"],
        "anantapur": ["andhra_pradesh", "andhra pradesh"],
        "arrah": ["bihar"],
        "karimnagar": ["telangana"],
        "parbhani": ["maharashtra"],
        "etawah": ["uttar_pradesh", "uttar pradesh"],
        "bharatpur": ["rajasthan"],
        "begusarai": ["bihar"],
        "new delhi": ["delhi", "delhi_(nct)"],
        "chhapra": ["bihar", "gujarat"],
        "kadapa": ["andhra_pradesh", "andhra pradesh"],
        "ramagundam": ["telangana"],
        "satna": ["madhya_pradesh", "madhya pradesh"],
        "vizianagaram": ["andhra_pradesh", "andhra pradesh"],
        "katihar": ["bihar"],
        "hardwar": ["uttarakhand"],
        "sonipat": ["haryana"],
        "nagercoil": ["tamil_nadu", "tamil nadu"],
        "kanyakumari": ["tamil_nadu", "tamil nadu"],
        "thanjavur": ["tamil_nadu", "tamil nadu"],
        "murwara (katni)": ["madhya_pradesh", "madhya pradesh"],
        "naihati": ["west_bengal", "west bengal"],
        "sambhal": ["uttar_pradesh", "uttar pradesh"],
        "nadiad": ["gujarat"],
        "yamunanagar": ["haryana"],
        "english bazar": ["west_bengal", "west bengal"],
        "eluru": ["andhra_pradesh", "andhra pradesh"],
        "munger": ["bihar"],
        "panchkula": ["haryana"],
        "raayachuru": ["karnataka"],
        "panvel": ["maharashtra"],
        "deoghar": ["jharkhand"],
        "ongole": ["andhra_pradesh", "andhra pradesh"],
        "nandyal": ["andhra_pradesh", "andhra pradesh"],
        "morena": ["madhya_pradesh", "madhya pradesh"],
        "bhiwani": ["haryana"],
        "porbandar": ["gujarat"],
        "palakkad": ["kerala"],
        "anand": ["gujarat"],
        "purnia": ["bihar"],
        "baharampur": ["west_bengal", "west bengal"],
        "barmer": ["rajasthan"],
        "morvi": ["gujarat"],
        "orai": ["uttar_pradesh", "uttar pradesh"],
        "bahraich": ["uttar_pradesh", "uttar pradesh"],
        "sikar": ["rajasthan"],
        "vellore": ["tamil_nadu", "tamil nadu"],
        "singrauli": ["madhya_pradesh", "madhya pradesh"],
        "khammam": ["telangana"],
        "mahesana": ["gujarat"],
        "silchar": ["assam"],
        "sambalpur": ["odisha"],
        "rewa": ["madhya_pradesh", "madhya pradesh"],
        "unnao": ["uttar_pradesh", "uttar pradesh"],
        "hugli-chinsurah": ["west_bengal", "west bengal"],
        "raiganj": ["west_bengal", "west bengal"],
        "phusro": ["jharkhand"],
        "adityapur": ["jharkhand"],
        "alappuzha": ["kerala"],
        "bahadurgarh": ["haryana"],
        "machilipatnam": ["andhra_pradesh", "andhra pradesh"],
        "rae bareli": ["uttar_pradesh", "uttar pradesh"],
        "jalpaiguri": ["west_bengal", "west bengal"],
        "bharuch": ["gujarat"],
        "pathankot": ["punjab"],
        "hoshiarpur": ["punjab"],
        "baramula": ["jammu_and_kashmir", "jammu and kashmir"],
        "adoni": ["andhra_pradesh", "andhra pradesh"],
        "jind": ["haryana"],
        "tonk": ["rajasthan"],
        "tenali": ["andhra_pradesh", "andhra pradesh"],
        "kancheepuram": ["tamil_nadu", "tamil nadu"],
        "sirsa": ["haryana"],
        "navsari": ["gujarat"],
        "mahbubnagar": ["telangana"],
        "puri": ["odisha"],
        "robertson pet": ["karnataka"],
        "erode": ["tamil_nadu", "tamil nadu"],
        "batala": ["punjab"],
        "haldwani-cum-kathgodam": ["uttarakhand"],
        "vidisha": ["madhya_pradesh", "madhya pradesh"],
        "saharsa": ["bihar"],
        "thanesar": ["haryana"],
        "chittoor": ["andhra_pradesh", "andhra pradesh"],
        "veraval": ["gujarat"],
        "lakhimpur": ["uttar_pradesh", "uttar pradesh"],
        "sitapur": ["uttar_pradesh", "uttar pradesh"],
        "hindupur": ["andhra_pradesh", "andhra pradesh"],
        "santipur": ["west_bengal", "west bengal"],
        "balurghat": ["west_bengal", "west bengal"],
        "ganjbasoda": ["madhya_pradesh", "madhya pradesh"],
        "moga": ["punjab"],
        "proddatur": ["andhra_pradesh", "andhra pradesh"],
        "medinipur": ["west_bengal", "west bengal"],
        "habra": ["west_bengal", "west bengal"],
        "sasaram": ["bihar"],
        "hajipur": ["bihar"],
        "bhuj": ["gujarat"],
        "shivpuri": ["madhya_pradesh", "madhya pradesh"],
        "ranaghat": ["west_bengal", "west bengal"],
        "shimla": ["himachal pradesh"],
        "tiruvannamalai": ["tamil_nadu", "tamil nadu"],
        "kaithal": ["haryana"],
        "rajnandgaon": ["chhattisgarh"],
        "godhra": ["gujarat"],
        "hazaribag": ["jharkhand"],
        "bhimavaram": ["andhra_pradesh", "andhra pradesh"],
        "mandsaur": ["madhya_pradesh", "madhya pradesh"],
        "dibrugarh": ["assam"],
        "kolar": ["karnataka"],
        "bankura": ["west_bengal", "west bengal"],
        "mandya": ["karnataka"],
        "dehri-on-sone": ["bihar"],
        "madanapalle": ["andhra_pradesh", "andhra pradesh"],
        "malerkotla": ["punjab"],
        "lalitpur": ["uttar_pradesh", "uttar pradesh"],
        "bettiah": ["bihar"],
        "pollachi": ["tamil_nadu", "tamil nadu"],
        "khanna": ["punjab"],
        "neemuch": ["madhya_pradesh", "madhya pradesh"],
        "palwal": ["haryana"],
        "palanpur": ["gujarat"],
        "guntakal": ["andhra_pradesh", "andhra pradesh"],
        "nabadwip": ["west_bengal", "west bengal"],
        "udupi": ["karnataka"],
        "jagdalpur": ["chhattisgarh"],
        "motihari": ["bihar"],
        "pilibhit": ["uttar_pradesh", "uttar pradesh"],
        "dimapur": ["nagaland"],
        "mohali": ["punjab"],
        "sadulpur": ["rajasthan"],
        "rajapalayam": ["tamil_nadu", "tamil nadu"],
        "dharmavaram": ["andhra_pradesh", "andhra pradesh"],
        "kashipur": ["uttarakhand"],
        "sivakasi": ["tamil_nadu", "tamil nadu"],
        "darjiling": ["west_bengal", "west bengal"],
        "chikkamagaluru": ["karnataka"],
        "gudivada": ["andhra_pradesh", "andhra pradesh"],
        "baleshwar town": ["odisha"],
        "mancherial": ["telangana"],
        "srikakulam": ["andhra_pradesh", "andhra pradesh"],
        "adilabad": ["telangana"],
        "yavatmal": ["maharashtra"],
        "barnala": ["punjab"],
        "nagaon": ["assam"],
        "narasaraopet": ["andhra_pradesh", "andhra pradesh"],
        "raigarh": ["chhattisgarh"],
        "roorkee": ["uttarakhand"],
        "valsad": ["gujarat"],
        "ambikapur": ["chhattisgarh"],
        "giridih": ["jharkhand"],
        "chandausi": ["uttar_pradesh", "uttar pradesh"],
        "purulia": ["west_bengal", "west bengal"],
        "patan": ["gujarat"],
        "bagaha": ["bihar"],
        "hardoi ": ["uttar_pradesh", "uttar pradesh"],
        "achalpur": ["maharashtra"],
        "osmanabad": ["maharashtra"],
        "deesa": ["gujarat"],
        "nandurbar": ["maharashtra"],
        "azamgarh": ["uttar_pradesh", "uttar pradesh"],
        "ramgarh": ["jharkhand"],
        "firozpur": ["punjab"],
        "baripada town": ["odisha"],
        "karwar": ["karnataka"],
        "siwan": ["bihar"],
        "rajampet": ["andhra_pradesh", "andhra pradesh"],
        "pudukkottai": ["tamil_nadu", "tamil nadu"],
        "anantnag": ["jammu_and_kashmir", "jammu and kashmir"],
        "tadpatri": ["andhra_pradesh", "andhra pradesh"],
        "satara": ["maharashtra"],
        "bhadrak": ["odisha"],
        "kishanganj": ["bihar"],
        "suryapet": ["telangana"],
        "wardha": ["maharashtra"],
        "ranebennuru": ["karnataka"],
        "amreli": ["gujarat"],
        "neyveli (ts)": ["tamil_nadu", "tamil nadu"],
        "jamalpur": ["bihar"],
        "marmagao": ["goa"],
        "udgir": ["maharashtra"],
        "tadepalligudem": ["andhra_pradesh", "andhra pradesh"],
        "nagapattinam": ["tamil_nadu", "tamil nadu"],
        "buxar": ["bihar"],
        "aurangabad": ["maharashtra", "bihar"],
        "jehanabad": ["bihar"],
        "phagwara": ["punjab"],
        "khair": ["uttar_pradesh", "uttar pradesh"],
        "sawai madhopur": ["rajasthan"],
        "kapurthala": ["punjab"],
        "chilakaluripet": ["andhra_pradesh", "andhra pradesh"],
        "malappuram": ["kerala"],
        "rewari": ["haryana"],
        "nagaur": ["rajasthan"],
        "sultanpur": ["uttar_pradesh", "uttar pradesh"],
        "nagda": ["madhya_pradesh", "madhya pradesh"],
        "port blair": ["andaman and nicobar islands"],
        "lakhisarai": ["bihar"],
        "panaji": ["goa"],
        "tinsukia": ["assam"],
        "itarsi": ["madhya_pradesh", "madhya pradesh"],
        "kohima": ["nagaland"],
        "balangir": ["odisha"],
        "nawada": ["bihar"],
        "jharsuguda": ["odisha"],
        "jagtial": ["telangana"],
        "viluppuram": ["tamil_nadu", "tamil nadu"],
        "amalner": ["maharashtra"],
        "zirakpur": ["punjab"],
        "tanda": ["uttar_pradesh", "uttar pradesh"],
        "tiruchengode": ["tamil_nadu", "tamil nadu"],
        "nagina": ["uttar_pradesh", "uttar pradesh"],
        "yemmiganur": ["andhra_pradesh", "andhra pradesh"],
        "vaniyambadi": ["tamil_nadu", "tamil nadu"],
        "sarni": ["madhya_pradesh", "madhya pradesh"],
        "theni allinagaram": ["tamil_nadu", "tamil nadu"],
        "margao": ["goa"],
        "akot": ["maharashtra"],
        "sehore": ["madhya_pradesh", "madhya pradesh"],
        "mhow cantonment": ["madhya_pradesh", "madhya pradesh"],
        "kot kapura": ["punjab"],
        "makrana": ["rajasthan"],
        "pandharpur": ["maharashtra"],
        "miryalaguda": ["telangana"],
        "shamli": ["uttar_pradesh", "uttar pradesh"],
        "seoni": ["madhya_pradesh", "madhya pradesh"],
        "ranibennur": ["karnataka"],
        "kadiri": ["andhra_pradesh", "andhra pradesh"],
        "shrirampur": ["maharashtra"],
        "rudrapur": ["uttarakhand", "uttar_pradesh", "uttar pradesh"],
        "parli": ["maharashtra"],
        "najibabad": ["uttar_pradesh", "uttar pradesh"],
        "nirmal": ["telangana"],
        "udhagamandalam": ["tamil_nadu", "tamil nadu"],
        "shikohabad": ["uttar_pradesh", "uttar pradesh"],
        "jhumri tilaiya": ["jharkhand"],
        "aruppukkottai": ["tamil_nadu", "tamil nadu"],
        "ponnani": ["kerala"],
        "jamui": ["bihar"],
        "sitamarhi": ["bihar"],
        "chirala": ["andhra_pradesh", "andhra pradesh"],
        "anjar": ["gujarat"],
        "karaikal": ["puducherry"],
        "hansi": ["haryana"],
        "anakapalle": ["andhra_pradesh", "andhra pradesh"],
        "mahasamund": ["chhattisgarh"],
        "faridkot": ["punjab"],
        "saunda": ["jharkhand"],
        "dhoraji": ["gujarat"],
        "paramakudi": ["tamil_nadu", "tamil nadu"],
        "balaghat": ["madhya_pradesh", "madhya pradesh"],
        "sujangarh": ["rajasthan"],
        "khambhat": ["gujarat"],
        "muktsar": ["punjab"],
        "rajpura": ["punjab"],
        "kavali": ["andhra_pradesh", "andhra pradesh"],
        "dhamtari": ["chhattisgarh"],
        "ashok nagar": ["madhya_pradesh", "madhya pradesh"],
        "sardarshahar": ["rajasthan"],
        "mahuva": ["gujarat"],
        "bargarh": ["odisha"],
        "kamareddy": ["telangana"],
        "sahibganj": ["jharkhand"],
        "kothagudem": ["telangana"],
        "ramanagaram": ["karnataka"],
        "gokak": ["karnataka"],
        "tikamgarh": ["madhya_pradesh", "madhya pradesh"],
        "araria": ["bihar"],
        "rishikesh": ["uttarakhand"],
        "shahdol": ["madhya_pradesh", "madhya pradesh"],
        "medininagar (daltonganj)": ["jharkhand"],
        "arakkonam": ["tamil_nadu", "tamil nadu"],
        "washim": ["maharashtra"],
        "sangrur": ["punjab"],
        "bodhan": ["telangana"],
        "fazilka": ["punjab"],
        "palacole": ["andhra_pradesh", "andhra pradesh"],
        "keshod": ["gujarat"],
        "sullurpeta": ["andhra_pradesh", "andhra pradesh"],
        "wadhwan": ["gujarat"],
        "gurdaspur": ["punjab"],
        "vatakara": ["kerala"],
        "tura": ["meghalaya"],
        "narnaul": ["haryana"],
        "kharar": ["punjab"],
        "yadgir": ["karnataka"],
        "ambejogai": ["maharashtra"],
        "ankleshwar": ["gujarat"],
        "savarkundla": ["gujarat"],
        "paradip": ["odisha"],
        "virudhachalam": ["tamil_nadu", "tamil nadu"],
        "kanhangad": ["kerala"],
        "kadi": ["gujarat"],
        "srivilliputhur": ["tamil_nadu", "tamil nadu"],
        "gobindgarh": ["punjab"],
        "tindivanam": ["tamil_nadu", "tamil nadu"],
        "taliparamba": ["kerala"],
        "manmad": ["maharashtra"],
        "tanuku": ["andhra_pradesh", "andhra pradesh"],
        "rayachoti": ["andhra_pradesh", "andhra pradesh"],
        "virudhunagar": ["tamil_nadu", "tamil nadu"],
        "koyilandy": ["kerala"],
        "jorhat": ["assam"],
        "karur": ["tamil_nadu", "tamil nadu"],
        "valparai": ["tamil_nadu", "tamil nadu"],
        "srikalahasti": ["andhra_pradesh", "andhra pradesh"],
        "neyyattinkara": ["kerala"],
        "bapatla": ["andhra_pradesh", "andhra pradesh"],
        "fatehabad": ["haryana"],
        "malout": ["punjab"],
        "sankarankovil": ["tamil_nadu", "tamil nadu"],
        "tenkasi": ["tamil_nadu", "tamil nadu"],
        "ratnagiri": ["maharashtra"],
        "rabkavi banhatti": ["karnataka"],
        "sikandrabad": ["uttar_pradesh", "uttar pradesh"],
        "chaibasa": ["jharkhand"],
        "chirmiri": ["chhattisgarh"],
        "palwancha": ["telangana"],
        "bhawanipatna": ["odisha"],
        "kayamkulam": ["kerala"],
        "pithampur": ["madhya_pradesh", "madhya pradesh"],
        "nabha": ["punjab"],
        "shahabad, hardoi": ["uttar_pradesh", "uttar pradesh"],
        "dhenkanal": ["odisha"],
        "uran islampur": ["maharashtra"],
        "gopalganj": ["bihar"],
        "bongaigaon city": ["assam"],
        "palani": ["tamil_nadu", "tamil nadu"],
        "pusad": ["maharashtra"],
        "sopore": ["jammu_and_kashmir", "jammu and kashmir"],
        "pilkhuwa": ["uttar_pradesh", "uttar pradesh"],
        "tarn taran": ["punjab"],
        "renukoot": ["uttar_pradesh", "uttar pradesh"],
        "mandamarri": ["telangana"],
        "shahabad": ["karnataka"],
        "barbil": ["odisha"],
        "koratla": ["telangana"],
        "madhubani": ["bihar"],
        "arambagh": ["west_bengal", "west bengal"],
        "gohana": ["haryana"],
        "ladnu": ["rajasthan"],
        "pattukkottai": ["tamil_nadu", "tamil nadu"],
        "sirsi": ["karnataka", "uttar_pradesh", "uttar pradesh"],
        "sircilla": ["telangana"],
        "tamluk": ["west_bengal", "west bengal"],
        "jagraon": ["punjab"],
        "alipurdurban agglomerationr": ["west_bengal", "west bengal"],
        "alirajpur": ["madhya_pradesh", "madhya pradesh"],
        "tandur": ["telangana"],
        "naidupet": ["andhra_pradesh", "andhra pradesh"],
        "tirupathur": ["tamil_nadu", "tamil nadu"],
        "tohana": ["haryana"],
        "ratangarh": ["rajasthan"],
        "dhubri": ["assam"],
        "masaurhi": ["bihar"],
        "visnagar": ["gujarat"],
        "vrindavan": ["uttar_pradesh", "uttar pradesh"],
        "nagari": ["andhra_pradesh", "andhra pradesh"],
        "narwana": ["haryana"],
        "ramanathapuram": ["tamil_nadu", "tamil nadu"],
        "ujhani": ["uttar_pradesh", "uttar pradesh"],
        "samastipur": ["bihar"],
        "laharpur": ["uttar_pradesh", "uttar pradesh"],
        "sangamner": ["maharashtra"],
        "nimbahera": ["rajasthan"],
        "siddipet": ["telangana"],
        "suri": ["west_bengal", "west bengal"],
        "diphu": ["assam"],
        "jhargram": ["west_bengal", "west bengal"],
        "shirpur-warwade": ["maharashtra"],
        "tilhar": ["uttar_pradesh", "uttar pradesh"],
        "sindhnur": ["karnataka"],
        "udumalaipettai": ["tamil_nadu", "tamil nadu"],
        "malkapur": ["maharashtra"],
        "wanaparthy": ["telangana"],
        "gudur": ["andhra_pradesh", "andhra pradesh"],
        "kendujhar": ["odisha"],
        "mandla": ["madhya_pradesh", "madhya pradesh"],
        "mandi": ["himachal pradesh"],
        "nedumangad": ["kerala"],
        "north lakhimpur": ["assam"],
        "vinukonda": ["andhra_pradesh", "andhra pradesh"],
        "tiptur": ["karnataka"],
        "gobichettipalayam": ["tamil_nadu", "tamil nadu"],
        "sunabeda": ["odisha"],
        "wani": ["maharashtra"],
        "upleta": ["gujarat"],
        "narasapuram": ["andhra_pradesh", "andhra pradesh"],
        "nuzvid": ["andhra_pradesh", "andhra pradesh"],
        "tezpur": ["assam"],
        "una": ["gujarat"],
        "markapur": ["andhra_pradesh", "andhra pradesh"],
        "sheopur": ["madhya_pradesh", "madhya pradesh"],
        "thiruvarur": ["tamil_nadu", "tamil nadu"],
        "sidhpur": ["gujarat"],
        "sahaswan": ["uttar_pradesh", "uttar pradesh"],
        "suratgarh": ["rajasthan"],
        "shajapur": ["madhya_pradesh", "madhya pradesh"],
        "rayagada": ["odisha"],
        "lonavla": ["maharashtra"],
        "ponnur": ["andhra_pradesh", "andhra pradesh"],
        "kagaznagar": ["telangana"],
        "gadwal": ["telangana"],
        "bhatapara": ["chhattisgarh"],
        "kandukur": ["andhra_pradesh", "andhra pradesh"],
        "sangareddy": ["telangana"],
        "unjha": ["gujarat"],
        "lunglei": ["mizoram"],
        "karimganj": ["assam"],
        "kannur": ["kerala"],
        "bobbili": ["andhra_pradesh", "andhra pradesh"],
        "mokameh": ["bihar"],
        "talegaon dabhade": ["maharashtra"],
        "anjangaon": ["maharashtra"],
        "sunam": ["punjab"],
        "gangarampur": ["west_bengal", "west bengal"],
        "thiruvallur": ["tamil_nadu", "tamil nadu"],
        "tirur": ["kerala"],
        "rath": ["uttar_pradesh", "uttar pradesh"],
        "jatani": ["odisha"],
        "viramgam": ["gujarat"],
        "rajsamand": ["rajasthan"],
        "yanam": ["puducherry"],
        "kottayam": ["kerala"],
        "panruti": ["tamil_nadu", "tamil nadu"],
        "dhuri": ["punjab"],
        "namakkal": ["tamil_nadu", "tamil nadu"],
        "kasaragod": ["kerala"],
        "modasa": ["gujarat"],
        "rayadurg": ["andhra_pradesh", "andhra pradesh"],
        "supaul": ["bihar"],
        "kunnamkulam": ["kerala"],
        "umred": ["maharashtra"],
        "bellampalle": ["telangana"],
        "sibsagar": ["assam"],
        "mandi dabwali": ["haryana"],
        "ottappalam": ["kerala"],
        "dumraon": ["bihar"],
        "samalkot": ["andhra_pradesh", "andhra pradesh"],
        "jaggaiahpet": ["andhra_pradesh", "andhra pradesh"],
        "goalpara": ["assam"],
        "tuni": ["andhra_pradesh", "andhra pradesh"],
        "lachhmangarh": ["rajasthan"],
        "bhongir": ["telangana"],
        "amalapuram": ["andhra_pradesh", "andhra pradesh"],
        "firozpur cantt.": ["punjab"],
        "vikarabad": ["telangana"],
        "thiruvalla": ["kerala"],
        "sherkot": ["uttar_pradesh", "uttar pradesh"],
        "palghar": ["maharashtra"],
        "shegaon": ["maharashtra"],
        "jangaon": ["telangana"],
        "bheemunipatnam": ["andhra_pradesh", "andhra pradesh"],
        "panna": ["madhya_pradesh", "madhya pradesh"],
        "thodupuzha": ["kerala"],
        "kathurban agglomeration": ["jammu_and_kashmir", "jammu and kashmir"],
        "palitana": ["gujarat"],
        "arwal": ["bihar"],
        "venkatagiri": ["andhra_pradesh", "andhra pradesh"],
        "kalpi": ["uttar_pradesh", "uttar pradesh"],
        "rajgarh (churu)": ["rajasthan"],
        "sattenapalle": ["andhra_pradesh", "andhra pradesh"],
        "arsikere": ["karnataka"],
        "ozar": ["maharashtra"],
        "thirumangalam": ["tamil_nadu", "tamil nadu"],
        "petlad": ["gujarat"],
        "nasirabad": ["rajasthan"],
        "phaltan": ["maharashtra"],
        "rampurhat": ["west_bengal", "west bengal"],
        "nanjangud": ["karnataka"],
        "forbesganj": ["bihar"],
        "tundla": ["uttar_pradesh", "uttar pradesh"],
        "bhaburban agglomeration": ["bihar"],
        "sagara": ["karnataka"],
        "pithapuram": ["andhra_pradesh", "andhra pradesh"],
        "sira": ["karnataka"],
        "bhadrachalam": ["telangana"],
        "charkhi dadri": ["haryana"],
        "chatra": ["jharkhand"],
        "palasa kasibugga": ["andhra_pradesh", "andhra pradesh"],
        "nohar": ["rajasthan"],
        "yevla": ["maharashtra"],
        "sirhind fatehgarh sahib": ["punjab"],
        "bhainsa": ["telangana"],
        "parvathipuram": ["andhra_pradesh", "andhra pradesh"],
        "shahade": ["maharashtra"],
        "chalakudy": ["kerala"],
        "narkatiaganj": ["bihar"],
        "kapadvanj": ["gujarat"],
        "macherla": ["andhra_pradesh", "andhra pradesh"],
        "raghogarh-vijaypur": ["madhya_pradesh", "madhya pradesh"],
        "rupnagar": ["punjab"],
        "naugachhia": ["bihar"],
        "sendhwa": ["madhya_pradesh", "madhya pradesh"],
        "byasanagar": ["odisha"],
        "sandila": ["uttar_pradesh", "uttar pradesh"],
        "gooty": ["andhra_pradesh", "andhra pradesh"],
        "salur": ["andhra_pradesh", "andhra pradesh"],
        "nanpara": ["uttar_pradesh", "uttar pradesh"],
        "sardhana": ["uttar_pradesh", "uttar pradesh"],
        "vita": ["maharashtra"],
        "gumia": ["jharkhand"],
        "jalandhar cantt.": ["punjab"],
        "nehtaur": ["uttar_pradesh", "uttar pradesh"],
        "changanassery": ["kerala"],
        "mandapeta": ["andhra_pradesh", "andhra pradesh"],
        "dumka": ["jharkhand"],
        "seohara": ["uttar_pradesh", "uttar pradesh"],
        "umarkhed": ["maharashtra"],
        "madhupur": ["jharkhand"],
        "vikramasingapuram": ["tamil_nadu", "tamil nadu"],
        "punalur": ["kerala"],
        "kendrapara": ["odisha"],
        "sihor": ["gujarat"],
        "nellikuppam": ["tamil_nadu", "tamil nadu"],
        "samana": ["punjab"],
        "warora": ["maharashtra"],
        "nilambur": ["kerala"],
        "rasipuram": ["tamil_nadu", "tamil nadu"],
        "ramnagar": ["uttarakhand", "bihar"],
        "jammalamadugu": ["andhra_pradesh", "andhra pradesh"],
        "nawanshahr": ["punjab"],
        "thoubal": ["manipur"],
        "athni": ["karnataka"],
        "cherthala": ["kerala"],
        "sidhi": ["madhya_pradesh", "madhya pradesh"],
        "farooqnagar": ["telangana"],
        "peddapuram": ["andhra_pradesh", "andhra pradesh"],
        "chirkunda": ["jharkhand"],
        "pachora": ["maharashtra"],
        "madhepura": ["bihar"],
        "pithoragarh": ["uttarakhand"],
        "tumsar": ["maharashtra"],
        "phalodi": ["rajasthan"],
        "tiruttani": ["tamil_nadu", "tamil nadu"],
        "rampura phul": ["punjab"],
        "perinthalmanna": ["kerala"],
        "padrauna": ["uttar_pradesh", "uttar pradesh"],
        "pipariya": ["madhya_pradesh", "madhya pradesh"],
        "dalli-rajhara": ["chhattisgarh"],
        "punganur": ["andhra_pradesh", "andhra pradesh"],
        "mattannur": ["kerala"],
        "mathura": ["uttar_pradesh", "uttar pradesh"],
        "thakurdwara": ["uttar_pradesh", "uttar pradesh"],
        "nandivaram-guduvancheri": ["tamil_nadu", "tamil nadu"],
        "mulbagal": ["karnataka"],
        "manjlegaon": ["maharashtra"],
        "wankaner": ["gujarat"],
        "sillod": ["maharashtra"],
        "nidadavole": ["andhra_pradesh", "andhra pradesh"],
        "surapura": ["karnataka"],
        "rajagangapur": ["odisha"],
        "sheikhpura": ["bihar"],
        "parlakhemundi": ["odisha"],
        "kalimpong": ["west_bengal", "west bengal"],
        "siruguppa": ["karnataka"],
        "arvi": ["maharashtra"],
        "limbdi": ["gujarat"],
        "barpeta": ["assam"],
        "manglaur": ["uttarakhand"],
        "repalle": ["andhra_pradesh", "andhra pradesh"],
        "mudhol": ["karnataka"],
        "shujalpur": ["madhya_pradesh", "madhya pradesh"],
        "mandvi": ["gujarat"],
        "thangadh": ["gujarat"],
        "sironj": ["madhya_pradesh", "madhya pradesh"],
        "nandura": ["maharashtra"],
        "shoranur": ["kerala"],
        "nathdwara": ["rajasthan"],
        "periyakulam": ["tamil_nadu", "tamil nadu"],
        "sultanganj": ["bihar"],
        "medak": ["telangana"],
        "narayanpet": ["telangana"],
        "raxaul bazar": ["bihar"],
        "rajauri": ["jammu_and_kashmir", "jammu and kashmir"],
        "pernampattu": ["tamil_nadu", "tamil nadu"],
        "nainital": ["uttarakhand"],
        "ramachandrapuram": ["andhra_pradesh", "andhra pradesh"],
        "vaijapur": ["maharashtra"],
        "nangal": ["punjab"],
        "sidlaghatta": ["karnataka"],
        "punch": ["jammu_and_kashmir", "jammu and kashmir"],
        "pandhurna": ["madhya_pradesh", "madhya pradesh"],
        "wadgaon road": ["maharashtra"],
        "talcher": ["odisha"],
        "varkala": ["kerala"],
        "pilani": ["rajasthan"],
        "nowgong": ["madhya_pradesh", "madhya pradesh"],
        "naila janjgir": ["chhattisgarh"],
        "mapusa": ["goa"],
        "vellakoil": ["tamil_nadu", "tamil nadu"],
        "merta city": ["rajasthan"],
        "sivaganga": ["tamil_nadu", "tamil nadu"],
        "mandideep": ["madhya_pradesh", "madhya pradesh"],
        "sailu": ["maharashtra"],
        "vyara": ["gujarat"],
        "kovvur": ["andhra_pradesh", "andhra pradesh"],
        "vadalur": ["tamil_nadu", "tamil nadu"],
        "nawabganj": ["uttar_pradesh", "uttar pradesh"],
        "padra": ["gujarat"],
        "sainthia": ["west_bengal", "west bengal"],
        "siana": ["uttar_pradesh", "uttar pradesh"],
        "shahpur": ["karnataka"],
        "sojat": ["rajasthan"],
        "noorpur": ["uttar_pradesh", "uttar pradesh"],
        "paravoor": ["kerala"],
        "murtijapur": ["maharashtra"],
        "sundargarh": ["odisha"],
        "taki": ["west_bengal", "west bengal"],
        "saundatti-yellamma": ["karnataka"],
        "pathanamthitta": ["kerala"],
        "wadi": ["karnataka"],
        "rameshwaram": ["tamil_nadu", "tamil nadu"],
        "tasgaon": ["maharashtra"],
        "sikandra rao": ["uttar_pradesh", "uttar pradesh"],
        "sihora": ["madhya_pradesh", "madhya pradesh"],
        "tiruvethipuram": ["tamil_nadu", "tamil nadu"],
        "tiruvuru": ["andhra_pradesh", "andhra pradesh"],
        "mehkar": ["maharashtra"],
        "peringathur": ["kerala"],
        "perambalur": ["tamil_nadu", "tamil nadu"],
        "manvi": ["karnataka"],
        "zunheboto": ["nagaland"],
        "mahnar bazar": ["bihar"],
        "attingal": ["kerala"],
        "shahbad": ["haryana"],
        "puranpur": ["uttar_pradesh", "uttar pradesh"],
        "nelamangala": ["karnataka"],
        "nakodar": ["punjab"],
        "lunawada": ["gujarat"],
        "murshidabad": ["west_bengal", "west bengal"],
        "mahe": ["puducherry"],
        "lanka": ["assam"],
        "rudauli": ["uttar_pradesh", "uttar pradesh"],
        "tuensang": ["nagaland"],
        "lakshmeshwar": ["karnataka"],
        "zira": ["punjab"],
        "yawal": ["maharashtra"],
        "thana bhawan": ["uttar_pradesh", "uttar pradesh"],
        "ramdurg": ["karnataka"],
        "pulgaon": ["maharashtra"],
        "sadasivpet": ["telangana"],
        "nargund": ["karnataka"],
        "neem-ka-thana": ["rajasthan"],
        "memari": ["west_bengal", "west bengal"],
        "nilanga": ["maharashtra"],
        "naharlagun": ["arunachal_pradesh", "arunachal pradesh"],
        "pakaur": ["jharkhand"],
        "wai": ["maharashtra"],
        "tarikere": ["karnataka"],
        "malavalli": ["karnataka"],
        "raisen": ["madhya_pradesh", "madhya pradesh"],
        "lahar": ["madhya_pradesh", "madhya pradesh"],
        "uravakonda": ["andhra_pradesh", "andhra pradesh"],
        "savanur": ["karnataka"],
        "sirohi": ["rajasthan"],
        "udhampur": ["jammu_and_kashmir", "jammu and kashmir"],
        "umarga": ["maharashtra"],
        "lingsugur": ["karnataka"],
        "usilampatti": ["tamil_nadu", "tamil nadu"],
        "palia kalan": ["uttar_pradesh", "uttar pradesh"],
        "wokha": ["nagaland"],
        "rajpipla": ["gujarat"],
        "vijayapura": ["karnataka"],
        "rawatbhata": ["rajasthan"],
        "sangaria": ["rajasthan"],
        "paithan": ["maharashtra"],
        "rahuri": ["maharashtra"],
        "patti": ["punjab"],
        "zaidpur": ["uttar_pradesh", "uttar pradesh"],
        "lalsot": ["rajasthan"],
        "maihar": ["madhya_pradesh", "madhya pradesh"],
        "vedaranyam": ["tamil_nadu", "tamil nadu"],
        "nawapur": ["maharashtra"],
        "solan": ["himachal pradesh"],
        "vapi": ["gujarat"],
        "sanawad": ["madhya_pradesh", "madhya pradesh"],
        "warisaliganj": ["bihar"],
        "revelganj": ["bihar"],
        "sabalgarh": ["madhya_pradesh", "madhya pradesh"],
        "tuljapur": ["maharashtra"],
        "simdega": ["jharkhand"],
        "musabani": ["jharkhand"],
        "kodungallur": ["kerala"],
        "phulabani": ["odisha"],
        "umreth": ["gujarat"],
        "narsipatnam": ["andhra_pradesh", "andhra pradesh"],
        "nautanwa": ["uttar_pradesh", "uttar pradesh"],
        "rajgir": ["bihar"],
        "yellandu": ["telangana"],
        "sathyamangalam": ["tamil_nadu", "tamil nadu"],
        "pilibanga": ["rajasthan"],
        "morshi": ["maharashtra"],
        "pehowa": ["haryana"],
        "sonepur": ["bihar"],
        "pappinisseri": ["kerala"],
        "zamania": ["uttar_pradesh", "uttar pradesh"],
        "mihijam": ["jharkhand"],
        "purna": ["maharashtra"],
        "puliyankudi": ["tamil_nadu", "tamil nadu"],
        "shikarpur, bulandshahr": ["uttar_pradesh", "uttar pradesh"],
        "umaria": ["madhya_pradesh", "madhya pradesh"],
        "porsa": ["madhya_pradesh", "madhya pradesh"],
        "naugawan sadat": ["uttar_pradesh", "uttar pradesh"],
        "fatehpur sikri": ["uttar_pradesh", "uttar pradesh"],
        "manuguru": ["telangana"],
        "udaipur": ["tripura", "rajasthan"],
        "pipar city": ["rajasthan"],
        "pattamundai": ["odisha"],
        "nanjikottai": ["tamil_nadu", "tamil nadu"],
        "taranagar": ["rajasthan"],
        "yerraguntla": ["andhra_pradesh", "andhra pradesh"],
        "satana": ["maharashtra"],
        "sherghati": ["bihar"],
        "sankeshwara": ["karnataka"],
        "madikeri": ["karnataka"],
        "thuraiyur": ["tamil_nadu", "tamil nadu"],
        "sanand": ["gujarat"],
        "rajula": ["gujarat"],
        "kyathampalle": ["telangana"],
        "shahabad, rampur": ["uttar_pradesh", "uttar pradesh"],
        "tilda newra": ["chhattisgarh"],
        "narsinghgarh": ["madhya_pradesh", "madhya pradesh"],
        "chittur-thathamangalam": ["kerala"],
        "malaj khand": ["madhya_pradesh", "madhya pradesh"],
        "sarangpur": ["madhya_pradesh", "madhya pradesh"],
        "robertsganj": ["uttar_pradesh", "uttar pradesh"],
        "sirkali": ["tamil_nadu", "tamil nadu"],
        "radhanpur": ["gujarat"],
        "tiruchendur": ["tamil_nadu", "tamil nadu"],
        "utraula": ["uttar_pradesh", "uttar pradesh"],
        "patratu": ["jharkhand"],
        "vijainagar, ajmer": ["rajasthan"],
        "periyasemur": ["tamil_nadu", "tamil nadu"],
        "pathri": ["maharashtra"],
        "sadabad": ["uttar_pradesh", "uttar pradesh"],
        "talikota": ["karnataka"],
        "sinnar": ["maharashtra"],
        "mungeli": ["chhattisgarh"],
        "sedam": ["karnataka"],
        "shikaripur": ["karnataka"],
        "sattur": ["tamil_nadu", "tamil nadu"],
        "sugauli": ["bihar"],
        "lumding": ["assam"],
        "vandavasi": ["tamil_nadu", "tamil nadu"],
        "titlagarh": ["odisha"],
        "uchgaon": ["maharashtra"],
        "mokokchung": ["nagaland"],
        "paschim punropara": ["west_bengal", "west bengal"],
        "sagwara": ["rajasthan"],
        "ramganj mandi": ["rajasthan"],
        "tarakeswar": ["west_bengal", "west bengal"],
        "mahalingapura": ["karnataka"],
        "dharmanagar": ["tripura"],
        "mahemdabad": ["gujarat"],
        "manendragarh": ["chhattisgarh"],
        "uran": ["maharashtra"],
        "tharamangalam": ["tamil_nadu", "tamil nadu"],
        "tirukkoyilur": ["tamil_nadu", "tamil nadu"],
        "pen": ["maharashtra"],
        "makhdumpur": ["bihar"],
        "maner": ["bihar"],
        "oddanchatram": ["tamil_nadu", "tamil nadu"],
        "palladam": ["tamil_nadu", "tamil nadu"],
        "mundi": ["madhya_pradesh", "madhya pradesh"],
        "nabarangapur": ["odisha"],
        "mudalagi": ["karnataka"],
        "samalkha": ["haryana"],
        "nepanagar": ["madhya_pradesh", "madhya pradesh"],
        "karjat": ["maharashtra"],
        "ranavav": ["gujarat"],
        "pedana": ["andhra_pradesh", "andhra pradesh"],
        "pinjore": ["haryana"],
        "lakheri": ["rajasthan"],
        "pasan": ["madhya_pradesh", "madhya pradesh"],
        "puttur": ["andhra_pradesh", "andhra pradesh", "karnataka"],
        "vadakkuvalliyur": ["tamil_nadu", "tamil nadu"],
        "tirukalukundram": ["tamil_nadu", "tamil nadu"],
        "mahidpur": ["madhya_pradesh", "madhya pradesh"],
        "mussoorie": ["uttarakhand"],
        "muvattupuzha": ["kerala"],
        "rasra": ["uttar_pradesh", "uttar pradesh"],
        "udaipurwati": ["rajasthan"],
        "manwath": ["maharashtra"],
        "adoor": ["kerala"],
        "uthamapalayam": ["tamil_nadu", "tamil nadu"],
        "partur": ["maharashtra"],
        "nahan": ["himachal pradesh"],
        "ladwa": ["haryana"],
        "mankachar": ["assam"],
        "nongstoin": ["meghalaya"],
        "losal": ["rajasthan"],
        "sri madhopur": ["rajasthan"],
        "ramngarh": ["rajasthan"],
        "mavelikkara": ["kerala"],
        "rawatsar": ["rajasthan"],
        "rajakhera": ["rajasthan"],
        "lar": ["uttar_pradesh", "uttar pradesh"],
        "lal gopalganj nindaura": ["uttar_pradesh", "uttar pradesh"],
        "muddebihal": ["karnataka"],
        "sirsaganj": ["uttar_pradesh", "uttar pradesh"],
        "shahpura": ["rajasthan"],
        "surandai": ["tamil_nadu", "tamil nadu"],
        "sangole": ["maharashtra"],
        "pavagada": ["karnataka"],
        "tharad": ["gujarat"],
        "mansa": ["gujarat", "punjab"],
        "umbergaon": ["gujarat"],
        "mavoor": ["kerala"],
        "nalbari": ["assam"],
        "talaja": ["gujarat"],
        "malur": ["karnataka"],
        "mangrulpir": ["maharashtra"],
        "soro": ["odisha"],
        "vadnagar": ["gujarat"],
        "raisinghnagar": ["rajasthan"],
        "sindhagi": ["karnataka"],
        "sanduru": ["karnataka"],
        "sohna": ["haryana"],
        "manavadar": ["gujarat"],
        "pihani": ["uttar_pradesh", "uttar pradesh"],
        "safidon": ["haryana"],
        "risod": ["maharashtra"],
        "rosera": ["bihar"],
        "sankari": ["tamil_nadu", "tamil nadu"],
        "malpura": ["rajasthan"],
        "sonamukhi": ["west_bengal", "west bengal"],
        "shamsabad, agra": ["uttar_pradesh", "uttar pradesh"],
        "nokha": ["bihar", "rajasthan"],
        "pandurban agglomeration": ["west_bengal", "west bengal"],
        "mainaguri": ["west_bengal", "west bengal"],
        "afzalpur": ["karnataka"],
        "shirur": ["maharashtra"],
        "salaya": ["gujarat"],
        "shenkottai": ["tamil_nadu", "tamil nadu"],
        "pratapgarh": ["tripura", "rajasthan"],
        "vadipatti": ["tamil_nadu", "tamil nadu"],
        "nagarkurnool": ["telangana"],
        "savner": ["maharashtra"],
        "sasvad": ["maharashtra"],
        "soron": ["uttar_pradesh", "uttar pradesh"],
        "sholingur": ["tamil_nadu", "tamil nadu"],
        "pandharkaoda": ["maharashtra"],
        "perumbavoor": ["kerala"],
        "maddur": ["karnataka"],
        "nadbai": ["rajasthan"],
        "talode": ["maharashtra"],
        "shrigonda": ["maharashtra"],
        "madhugiri": ["karnataka"],
        "tekkalakote": ["karnataka"],
        "seoni-malwa": ["madhya_pradesh", "madhya pradesh"],
        "shirdi": ["maharashtra"],
        "surban agglomerationr": ["uttar_pradesh", "uttar pradesh"],
        "terdal": ["karnataka"],
        "raver": ["maharashtra"],
        "taraori": ["haryana"],
        "mukhed": ["maharashtra"],
        "manachanallur": ["tamil_nadu", "tamil nadu"],
        "rehli": ["madhya_pradesh", "madhya pradesh"],
        "sanchore": ["rajasthan"],
        "rajura": ["maharashtra"],
        "piro": ["bihar"],
        "mudabidri": ["karnataka"],
        "vadgaon kasba": ["maharashtra"],
        "nagar": ["rajasthan"],
        "vijapur": ["gujarat"],
        "viswanatham": ["tamil_nadu", "tamil nadu"],
        "polur": ["tamil_nadu", "tamil nadu"],
        "panagudi": ["tamil_nadu", "tamil nadu"],
        "manawar": ["madhya_pradesh", "madhya pradesh"],
        "tehri": ["uttarakhand"],
        "samdhan": ["uttar_pradesh", "uttar pradesh"],
        "pardi": ["gujarat"],
        "rahatgarh": ["madhya_pradesh", "madhya pradesh"],
        "panagar": ["madhya_pradesh", "madhya pradesh"],
        "uthiramerur": ["tamil_nadu", "tamil nadu"],
        "tirora": ["maharashtra"],
        "rangia": ["assam"],
        "sahjanwa": ["uttar_pradesh", "uttar pradesh"],
        "wara seoni": ["madhya_pradesh", "madhya pradesh"],
        "magadi": ["karnataka"],
        "rajgarh (alwar)": ["rajasthan"],
        "rafiganj": ["bihar"],
        "tarana": ["madhya_pradesh", "madhya pradesh"],
        "rampur maniharan": ["uttar_pradesh", "uttar pradesh"],
        "sheoganj": ["rajasthan"],
        "raikot": ["punjab"],
        "pauri": ["uttarakhand"],
        "sumerpur": ["uttar_pradesh", "uttar pradesh", "rajasthan"],
        "navalgund": ["karnataka"],
        "shahganj": ["uttar_pradesh", "uttar pradesh"],
        "marhaura": ["bihar"],
        "tulsipur": ["uttar_pradesh", "uttar pradesh"],
        "sadri": ["rajasthan"],
        "thiruthuraipoondi": ["tamil_nadu", "tamil nadu"],
        "shiggaon": ["karnataka"],
        "pallapatti": ["tamil_nadu", "tamil nadu"],
        "mahendragarh": ["haryana"],
        "sausar": ["madhya_pradesh", "madhya pradesh"],
        "ponneri": ["tamil_nadu", "tamil nadu"],
        "mahad": ["maharashtra"],
        "lohardaga": ["jharkhand"],
        "tirwaganj": ["uttar_pradesh", "uttar pradesh"],
        "margherita": ["assam"],
        "sundarnagar": ["himachal pradesh"],
        "rajgarh": ["madhya_pradesh", "madhya pradesh"],
        "mangaldoi": ["assam"],
        "renigunta": ["andhra_pradesh", "andhra pradesh"],
        "longowal": ["punjab"],
        "ratia": ["haryana"],
        "lalgudi": ["tamil_nadu", "tamil nadu"],
        "shrirangapattana": ["karnataka"],
        "niwari": ["madhya_pradesh", "madhya pradesh"],
        "natham": ["tamil_nadu", "tamil nadu"],
        "unnamalaikadai": ["tamil_nadu", "tamil nadu"],
        "purqurban agglomerationzi": ["uttar_pradesh", "uttar pradesh"],
        "shamsabad, farrukhabad": ["uttar_pradesh", "uttar pradesh"],
        "mirganj": ["bihar"],
        "todaraisingh": ["rajasthan"],
        "warhapur": ["uttar_pradesh", "uttar pradesh"],
        "rajam": ["andhra_pradesh", "andhra pradesh"],
        "urmar tanda": ["punjab"],
        "lonar": ["maharashtra"],
        "powayan": ["uttar_pradesh", "uttar pradesh"],
        "p.n.patti": ["tamil_nadu", "tamil nadu"],
        "palampur": ["himachal pradesh"],
        "srisailam project (right flank colony) township": ["andhra_pradesh", "andhra pradesh"],
        "sindagi": ["karnataka"],
        "sandi": ["uttar_pradesh", "uttar pradesh"],
        "vaikom": ["kerala"],
        "malda": ["west_bengal", "west bengal"],
        "tharangambadi": ["tamil_nadu", "tamil nadu"],
        "sakaleshapura": ["karnataka"],
        "malkangiri": ["odisha"],
        "rapar": ["gujarat"],
        "mauganj": ["madhya_pradesh", "madhya pradesh"],
        "todabhim": ["rajasthan"],
        "srinivaspur": ["karnataka"],
        "murliganj": ["bihar"],
        "reengus": ["rajasthan"],
        "sawantwadi": ["maharashtra"],
        "tittakudi": ["tamil_nadu", "tamil nadu"],
        "lilong": ["manipur"],
        "rajaldesar": ["rajasthan"],
        "pathardi": ["maharashtra"],
        "achhnera": ["uttar_pradesh", "uttar pradesh"],
        "pacode": ["tamil_nadu", "tamil nadu"],
        "naraura": ["uttar_pradesh", "uttar pradesh"],
        "nakur": ["uttar_pradesh", "uttar pradesh"],
        "palai": ["kerala"],
        "morinda, india": ["punjab"],
        "manasa": ["madhya_pradesh", "madhya pradesh"],
        "nainpur": ["madhya_pradesh", "madhya pradesh"],
        "sahaspur": ["uttar_pradesh", "uttar pradesh"],
        "pauni": ["maharashtra"],
        "prithvipur": ["madhya_pradesh", "madhya pradesh"],
        "ramtek": ["maharashtra"],
        "silapathar": ["assam"],
        "songadh": ["gujarat"],
        "safipur": ["uttar_pradesh", "uttar pradesh"],
        "sohagpur": ["madhya_pradesh", "madhya pradesh"],
        "mul": ["maharashtra"],
        "sadulshahar": ["rajasthan"],
        "phillaur": ["punjab"],
        "sambhar": ["rajasthan"],
        "prantij": ["rajasthan"],
        "nagla": ["uttarakhand"],
        "pattran": ["punjab"],
        "mount abu": ["rajasthan"],
        "reoti": ["uttar_pradesh", "uttar pradesh"],
        "tenu dam-cum-kathhara": ["jharkhand"],
        "panchla": ["west_bengal", "west bengal"],
        "sitarganj": ["uttarakhand"],
        "pasighat": ["arunachal_pradesh", "arunachal pradesh"],
        "motipur": ["bihar"],
        "o' valley": ["tamil_nadu", "tamil nadu"],
        "raghunathpur": ["west_bengal", "west bengal"],
        "suriyampalayam": ["tamil_nadu", "tamil nadu"],
        "qadian": ["punjab"],
        "rairangpur": ["odisha"],
        "silvassa": ["dadra and nagar haveli"],
        "nowrozabad (khodargama)": ["madhya_pradesh", "madhya pradesh"],
        "mangrol": ["rajasthan", "gujarat"],
        "soyagaon": ["maharashtra"],
        "sujanpur": ["punjab"],
        "manihari": ["bihar"],
        "sikanderpur": ["uttar_pradesh", "uttar pradesh"],
        "mangalvedhe": ["maharashtra"],
        "phulera": ["rajasthan"],
        "ron": ["karnataka"],
        "sholavandan": ["tamil_nadu", "tamil nadu"],
        "saidpur": ["uttar_pradesh", "uttar pradesh"],
        "shamgarh": ["madhya_pradesh", "madhya pradesh"],
        "thammampatti": ["tamil_nadu", "tamil nadu"],
        "maharajpur": ["madhya_pradesh", "madhya pradesh"],
        "multai": ["madhya_pradesh", "madhya pradesh"],
        "mukerian": ["punjab"],
        "purwa": ["uttar_pradesh", "uttar pradesh"],
        "sheohar": ["bihar"],
        "namagiripettai": ["tamil_nadu", "tamil nadu"],
        "parasi": ["uttar_pradesh", "uttar pradesh"],
        "lathi": ["gujarat"],
        "lalganj": ["uttar_pradesh", "uttar pradesh", "bihar"],
        "narkhed": ["maharashtra"],
        "mathabhanga": ["west_bengal", "west bengal"],
        "shendurjana": ["maharashtra"],
        "peravurani": ["tamil_nadu", "tamil nadu"],
        "mariani": ["assam"],
        "phulpur": ["uttar_pradesh", "uttar pradesh"],
        "rania": ["haryana"],
        "pali": ["madhya_pradesh", "madhya pradesh", "rajasthan"],
        "pachore": ["madhya_pradesh", "madhya pradesh"],
        "parangipettai": ["tamil_nadu", "tamil nadu"],
        "pudupattinam": ["tamil_nadu", "tamil nadu"],
        "panniyannur": ["kerala"],
        "maharajganj": ["bihar"],
        "rau": ["madhya_pradesh", "madhya pradesh"],
        "monoharpur": ["west_bengal", "west bengal"],
        "mandawa": ["rajasthan"],
        "marigaon": ["assam"],
        "pallikonda": ["tamil_nadu", "tamil nadu"],
        "pindwara": ["rajasthan"],
        "shishgarh": ["uttar_pradesh", "uttar pradesh"],
        "patur": ["maharashtra"],
        "mayang imphal": ["manipur"],
        "mhowgaon": ["madhya_pradesh", "madhya pradesh"],
        "guruvayoor": ["kerala"],
        "mhaswad": ["maharashtra"],
        "sahawar": ["uttar_pradesh", "uttar pradesh"],
        "sivagiri": ["tamil_nadu", "tamil nadu"],
        "mundargi": ["karnataka"],
        "punjaipugalur": ["tamil_nadu", "tamil nadu"],
        "kailasahar": ["tripura"],
        "samthar": ["uttar_pradesh", "uttar pradesh"],
        "sakti": ["chhattisgarh"],
        "sadalagi": ["karnataka"],
        "silao": ["bihar"],
        "mandalgarh": ["rajasthan"],
        "loha": ["maharashtra"],
        "pukhrayan": ["uttar_pradesh", "uttar pradesh"],
        "padmanabhapuram": ["tamil_nadu", "tamil nadu"],
        "belonia": ["tripura"],
        "saiha": ["mizoram"],
        "srirampore": ["west_bengal", "west bengal"],
        "talwara": ["punjab"],
        "puthuppally": ["kerala"],
        "khowai": ["tripura"],
        "vijaypur": ["madhya_pradesh", "madhya pradesh"],
        "takhatgarh": ["rajasthan"],
        "thirupuvanam": ["tamil_nadu", "tamil nadu"],
        "adra": ["west_bengal", "west bengal"],
        "piriyapatna": ["karnataka"],
        "obra": ["uttar_pradesh", "uttar pradesh"],
        "adalaj": ["gujarat"],
        "nandgaon": ["maharashtra"],
        "barh": ["bihar"],
        "panamattom": ["kerala"],
        "niwai": ["uttar_pradesh", "uttar pradesh"],
        "bageshwar": ["uttarakhand"],
        "tarbha": ["odisha"],
        "adyar": ["karnataka"],
        "warud": ["maharashtra"],
        "asarganj": ["bihar"],
        "sarsod": ["haryana"],
    }
    return city_state_mapping.get(city.lower(), [])


def get_phone_area_code_for_city(city: str) -> str:
    city_area_code_mapping = {
        "agartala": "381",
        "agra": "562",
        "ahmedabad": "79",
        "aizawl": "389",
        "ajmer": "145",
        "akbarpur": "5271",
        "akola": "724",
        "alappuzha": "477",
        "aligarh": "571",
        "alipore": "33",
        "alwar": "144",
        "amravati": "721",
        "amritsar": "183",
        "amroha": "5922",
        "anand": "2692",
        "anantapur": "8554",
        "anantnag": "193",
        "angul": "6764",
        "araria": "6453",
        "arrah": "6182",
        "asansol": "341",
        "auraiya": "5683",
        "aurangabad": "2432",
        "azamgarh": "5462",
        "badaun": "5832",
        "bagpat": "1234",
        "baharampur": "3482",
        "bahraich": "5252",
        "balaghat": "7632",
        "balangir": "6652",
        "balasore": "6782",
        "ballia": "5498",
        "balrampur": "5263",
        "balurghat": "3522",
        "banda": "5192",
        "bangalore": "80",
        "banka": "6424",
        "bankura": "3242",
        "banswara": "2962",
        "barabanki": "5248",
        "baramulla": "1952",
        "baran": "7453",
        "barasat": "33",
        "barddhaman": "342",
        "bardhaman": "342",
        "bareilly": "581",
        "bargarh": "6646",
        "baripada": "6792",
        "barmer": "2982",
        "barnala": "1679",
        "baroda": "265",
        "barwani": "7290",
        "basti": "5542",
        "bathinda": "164",
        "beawar": "1462",
        "beed": "2442",
        "begusarai": "6243",
        "berhampur": "680",
        "bettiah": "6254",
        "betul": "7141",
        "bhabua": "6189",
        "bhadrachalam": "8743",
        "bhadrak": "6784",
        "bhagalpur": "641",
        "bhandara": "7184",
        "bharatpur": "5644",
        "bharuch": "2642",
        "bhavnagar": "278",
        "bhawanipatna": "6670",
        "bhilwara": "1482",
        "bhind": "7534",
        "bhinga": "5250",
        "bhopal": "755",
        "bhubaneshwar": "674",
        "bhubaneswar": "674",
        "bhuj": "2832",
        "bijnor": "1342",
        "bikaner": "151",
        "bokaro steel city": "6542",
        "bombay": "22",
        "boudh": "6841",
        "bulandshahr": "5732",
        "buldhana": "7262",
        "bundi": "747",
        "burhanpur": "7325",
        "buxar": "6183",
        "calcutta": "33",
        "chandauli": "5412",
        "chandigarh": "172",
        "chandrapur": "7172",
        "chennai": "44",
        "chennai (formerly madras)": "44",
        "chennai (madras)": "44",
        "cherrapunji": "3637",
        "chhapra": "6152",
        "chhatarpur": "7682",
        "chhatrapur": "6811",
        "chhindwara": "7162",
        "chitrakuta": "5194",
        "chittoor": "8572",
        "chittorgarh": "8572",
        "churu": "1562",
        "cochin (kochi)": "484",
        "coimbator": "422",
        "coimbatore": "422",
        "cooch behar": "3582",
        "cuddalore": "4142",
        "cuttack": "671",
        "daman": "260",
        "damoh": "7638",
        "darbhanga": "6272",
        "darjeeling": "354",
        "datia": "7522",
        "dausa": "1427",
        "debagarh": "6641",
        "dehra dun": "135",
        "dehradun": "135",
        "delhi": "11",
        "deogarh": "6432",
        "deoghar": "6432",
        "deoria": "5568",
        "dewas": "7272",
        "dhanbad": "326",
        "dhar": "7292",
        "dharmapuri": "4342",
        "dhenkanal": "6762",
        "dholpur": "5642",
        "dhule": "2562",
        "dibrugarh": "373",
        "dimapur": "3862",
        "dindigul": "451",
        "dispur": "361",
        "dungarpur": "2964",
        "eluru": "8812",
        "erode": "424",
        "etah": "5742",
        "etawah": "5688",
        "faizabad": "5278",
        "faridabad": "129",
        "faridkot": "1639",
        "fatehgarh": "5692",
        "fatehgarh sahib": "1763",
        "fatehpur": "5240",
        "fathepur sikri": "5619",
        "firozabad": "5612",
        "firozpur": "1632",
        "gadchiroli": "7132",
        "gandhinagar": "2712",
        "ganganagar": "154",
        "gangtok": "3592",
        "gaya": "631",
        "ghaziabad": "120",
        "ghazipur": "548",
        "giridih": "1933",
        "gonda": "5262",
        "gondia": "7182",
        "gopalganj": "6156",
        "gorakhpur": "551",
        "gumla": "6524",
        "guna": "7542",
        "guntur": "863",
        "gurdaspur": "1874",
        "gurgaon": "124",
        "guwahati": "361",
        "gwalior": "751",
        "gyanpur": "5414",
        "hajipur": "6224",
        "haldwani": "5946",
        "hamirpur": "5282",
        "hanumangarh": "1552",
        "harda": "7577",
        "hardoi": "5852",
        "haridwar": "1332",
        "hathras": "5722",
        "hazaribagh": "6546",
        "hingoli": "2456",
        "hoshangabad": "7574",
        "hoshiarpur": "1882",
        "howrah": "33",
        "hugli-chuchura": "33",
        "hyderabad": "40",
        "imphal": "3852",
        "indore": "731",
        "itanagar": "360",
        "jabalpur": "761",
        "jagatsinghpur": "6724",
        "jaipur": "141",
        "jaisalmer": "2922",
        "jalandhar": "181",
        "jalgaon": "257",
        "jalna": "2482",
        "jalore": "2972",
        "jalpaiguri": "3561",
        "jammu": "191",
        "jamnagar": "288",
        "jamshedpur": "657",
        "jamui": "6345",
        "jaunpur": "5452",
        "jehanabad": "6114",
        "jhabua": "7392",
        "jhalawar": "7432",
        "jhansi": "510",
        "jharsuguda": "6645",
        "jhunjhunu": "1595",
        "jodhpur": "291",
        "jullundur": "181",
        "junagadh": "285",
        "kalpetta": "4936",
        "kanchipuram": "44",
        "kannauj": "5694",
        "kanpur": "512",
        "kapurthala": "1822",
        "karauli": "7464",
        "karjat": "2489",
        "karur": "4324",
        "kasaragod": "494",
        "kathua": "1922",
        "katihar": "6452",
        "katni": "7622",
        "kavaratti": "4896",
        "kendrapara": "6727",
        "kendujhar": "6766",
        "khagaria": "6244",
        "khalilabad": "5547",
        "khandwa": "733",
        "kharagpur": "3222",
        "khargone": "7282",
        "khordha": "6755",
        "kishanganj": "6466",
        "kochi": "484",
        "kohima": "370",
        "kolhapur": "231",
        "kolkata": "33",
        "kolkata (calcutta)": "33",
        "kolkatta (formerly calcutta)": "33",
        "kollam": "474",
        "koraput": "6852",
        "kota": "744",
        "kottayam": "481",
        "kozhikode": "495",
        "krishnagiri": "4343",
        "krishnanagar": "3472",
        "kulti": "341",
        "lakhimpur": "5872",
        "lakhisarai": "6346",
        "lalitpur": "5176",
        "latur": "2382",
        "lucknow": "522",
        "ludhiana": "161",
        "madhepura": "6476",
        "madhubani": "6276",
        "madras": "44",
        "madurai": "452",
        "maharajganj": "5523",
        "mahoba": "5281",
        "mainpuri": "5672",
        "malda": "3512",
        "malkangiri": "6861",
        "mandla": "7642",
        "mandsaur": "7422",
        "manipal": "8252",
        "manjhanpur": "5331",
        "mansa": "1652",
        "margao": "8342",
        "mathura": "565",
        "mau": "5195",
        "meerut": "121",
        "midnapore": "3222",
        "mirzapur": "5442",
        "moga": "1636",
        "mohali": "172",
        "moradabad": "591",
        "morena": "7532",
        "motihari": "6252",
        "mount abu": "2974",
        "muktsar": "1633",
        "mumbai": "22",
        "mumbai (bombay)": "22",
        "mumbai (formerly bombay )": "22",
        "munger": "6344",
        "mussooree": "1362",
        "muzaffarnagar": "131",
        "muzaffarpur": "621",
        "mysore": "821",
        "nabarangpur": "685",
        "nadiad": "268",
        "nagaon": "3672",
        "nagapattinam": "4365",
        "nagaur": "1582",
        "nagercoil": "4652",
        "kanyakumari": "4652",
        "nagpur": "712",
        "nalanda": "6119",
        "namakkal": "4286",
        "nanded": "2462",
        "nandurbar": "2564",
        "narsinghpur": "7792",
        "nashik": "253",
        "nasik": "253",
        "naugarh": "5544",
        "navi mumbai": "22",
        "navsari": "2637",
        "nawabganj": "6324",
        "nawada": "6324",
        "nawanshahr": "1823",
        "nayagarh": "6753",
        "neemuch": "7423",
        "new delhi": "11",
        "new okhla industrial development authority": "120",
        "nuapada": "6678",
        "ootacamund": "423",
        "orai": "5162",
        "osmanabad": "2472",
        "padrauna": "5564",
        "painavu": "486",
        "palakkad": "491",
        "pampore": "1933",
        "panaji": "832",
        "panchkula": "172",
        "panipat": "180",
        "panna": "7732",
        "panskura": "3228",
        "panvel": "22",
        "paralakhemundi": "6815",
        "parbhani": "2452",
        "pathanamthitta": "468",
        "patiala": "175",
        "patna": "612",
        "perambalur": "4328",
        "phulbani": "6842",
        "pilibhit": "5882",
        "ponnani": "483",
        "port blair": "3192",
        "pratapgarh": "5342",
        "puducherry": "413",
        "pudukkottai": "4322",
        "pune": "20",
        "pune (formerly poona)": "20",
        "puri": "6752",
        "purnia": "6454",
        "purulia": "3252",
        "pushkar": "145",
        "rae bareli": "535",
        "raebareli": "535",
        "raiganj": "3523",
        "raipur": "771",
        "rajgarh": "7372",
        "rajkot": "281",
        "rajsamand": "2952",
        "ramanathapuram": "4567",
        "rampur": "595",
        "ranchi": "651",
        "ranthambhore natl. park": "7462",
        "ratlam": "7412",
        "ratnagiri": "2353",
        "rayagada": "6856",
        "rewa": "7662",
        "robertsganj": "5444",
        "roorkee": "1332",
        "rourkela": "661",
        "rupnagar": "1881",
        "sagar": "7582",
        "saharanpur": "132",
        "saharsa": "6478",
        "samastipur": "6274",
        "sambalpur": "663",
        "sangli": "233",
        "sangrur": "1672",
        "sariska": "144",
        "sasaram": "6184",
        "satara": "2162",
        "satna": "7672",
        "sawai madhopur": "7462",
        "sehore": "7562",
        "seoni": "7692",
        "shahdol": "7652",
        "shahjahanpur": "5842",
        "shajapur": "7364",
        "sheikhpura": "6341",
        "sheohar": "6222",
        "sheopur": "7530",
        "shillong": "364",
        "shimla": "177",
        "shivpuri": "7492",
        "sibsagar": "3772",
        "sidhi": "7822",
        "sikar": "1572",
        "silchar": "3842",
        "silvassa": "260",
        "simla": "177",
        "sindri": "326",
        "sitamarhi": "6226",
        "sitapur": "5862",
        "sivaganga": "4575",
        "siwan": "6154",
        "solapur": "217",
        "sonepur": "6654",
        "sopore": "1954",
        "srinagar": "194",
        "sultanpur": "5362",
        "sundergarh": "6622",
        "supaul": "6473",
        "surat": "261",
        "suri": "3462",
        "tamluk": "3228",
        "tarn taran sahib": "1852",
        "thalassery": "490",
        "thane": "22",
        "thanjavur": "4362",
        "theni": "4546",
        "thiruvan": "471",
        "thiruvananthapuram": "471",
        "thiruvannaamalai": "4175",
        "thoothukudi": "461",
        "thrissur": "487",
        "tikamgarh": "7683",
        "tinsukia": "374",
        "tiruchirapalli": "431",
        "tirumala": "877",
        "tirunelveli": "462",
        "tiruvallur": "44",
        "tiruvarur": "4366",
        "tonk": "1435",
        "udaipur": "294",
        "udhampur": "199",
        "ujjain": "734",
        "unnao": "515",
        "vadodara": "265",
        "vadodara (baroda)": "265",
        "varanasi": "542",
        "vasco da gama": "832",
        "vellore": "416",
        "vidisha": "7592",
        "vijayawada": "866",
        "viluppuram": "4146",
        "virudhunagar": "4562",
        "virudunagar": "4562",
        "visakhapatnam": "891",
        "warangal": "870",
        "wardha": "7152",
        "washim": "7252",
        "yavatmal": "7232"
    }
    return city_area_code_mapping.get(city, '')
